### PR TITLE
Instructions to connect CH with Grafana

### PR DESCRIPTION
**Pull request by anelook**
# What changed, and why it matters

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
Hi @anelook, could you please check the 2 warnings? Also please rebase since I just merged @FloorD article about the Grafana plugins containing the fix for Altinity.
Also this is missing the entry in the _toc file, now that the Kafka integration is merged, maybe you can fix it?

**Comment by ftisiot** [comment]
One note here, should this be under clickhouse, under grafana or under both?

**Comment by anelook** [comment]
@ftisiot , I've rebased with latest main and added _toc entry. Fixed one warning (haven't seen the second one). The update from Floor is just into the list of all existing Grafana plugins, right? Not a separate article (I checked and don't see one)

I do believe this article belongs  to CH part and will be discovered by customers looking what integrations are available to visualise data.

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
