### PR TITLE
migrate azure vnet peering article

### PR DESCRIPTION
**Pull request by encima**
# What changed, and why it matters

Migration of https://help.aiven.io/en/articles/3435096-azure-virtual-network-peering with changes to match Azure CLI (tested 18th Oct 2022).

There is a [PR](https://github.com/aiven/devportal/pull/1310) that mentions bringing this article in but it is not included.

### CODE REVIEW

**Comment by encima** [comment]
Changes to Azure CLI found by @etuomiko and @fmanimali 🙏

**Comment by dewan-ahmed** [comment]
Hi @encima @fmanimali please refer to https://github.com/aiven/devportal/pull/1408 on the structure for the VPC peering articles. 

For example, the _toc.yml entry for this article would go under:

- file: docs/platform/howto/list-network
        title: Network management

and a ref link will be needed on the general VPC peering page https://docs.aiven.io/docs/platform/howto/manage-vpc-peering.html. 

In case you're not working on the AWS VPC peering article, please let me know and I can create a PR for that one. Thanks.

**Comment by fmanimali** [comment]
> Hi @encima @fmanimali please refer to #1408 on the structure for the VPC peering articles.
> 
> For example, the _toc.yml entry for this article would go under:
> 
> * file: docs/platform/howto/list-network
>   title: Network management
> 
> and a ref link will be needed on the general VPC peering page https://docs.aiven.io/docs/platform/howto/manage-vpc-peering.html.
> 
> In case you're not working on the AWS VPC peering article, please let me know and I can create a PR for that one. Thanks.

**Comment by fmanimali** [comment]
> Hi @encima @fmanimali please refer to #1408 on the structure for the VPC peering articles.
> 
> For example, the _toc.yml entry for this article would go under:
> 
> * file: docs/platform/howto/list-network
>   title: Network management
> 
> and a ref link will be needed on the general VPC peering page https://docs.aiven.io/docs/platform/howto/manage-vpc-peering.html.
> 
> In case you're not working on the AWS VPC peering article, please let me know and I can create a PR for that one. Thanks.

I have added the link into _toc. let me know if that's ok. 

In which file does the link go? And how do i do that?

**Comment by encima** [comment]
> Hi @encima @fmanimali please refer to #1408 on the structure for the VPC peering articles.
> 
> For example, the _toc.yml entry for this article would go under:
> 
> * file: docs/platform/howto/list-network
>   title: Network management
> 
> and a ref link will be needed on the general VPC peering page https://docs.aiven.io/docs/platform/howto/manage-vpc-peering.html.
> 
> In case you're not working on the AWS VPC peering article, please let me know and I can create a PR for that one. Thanks.

This is done. I am not working on the AWS VPC so please feel free

**Comment by dewan-ahmed** [comment]
Thanks for this addition @encima @fmanimali 

Since the technical review is done from your end, I'll review this from an editorial angle and add entries to the migration sheet after merging (since this is a migration task).

Related PR: https://github.com/aiven/devportal/pull/1487 (appreciate your technical review on this).

**Review by fmanimali — APPROVED** [review]

**Comment by fmanimali** [comment]
@dewan-ahmed are you good to merge?

**Comment by dewan-ahmed** [comment]
thanks for reviewing @encima 
I was on the road last week and was going to review today.

**Pull request merged**
