### PR TITLE
Migrate service level agreement

### PR DESCRIPTION
**Pull request by sluhur**
# What changed, and why it matters

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
Sorry I've been confused a bit, let me review again

**Review by ftisiot — CHANGES_REQUESTED** [review]
Ok, I was confused since the PR also includes stuff coming from #1257 since contains both SLA and corporate billing?
Can we split the two please, and remove from here the corporate billing section? If it's better please close this and open a new PR

**Comment by sluhur** [comment]
> Ok, I was confused since the PR also includes stuff coming from #1257 since contains both SLA and corporate billing? Can we split the two please, and remove from here the corporate billing section? If it's better please close this and open a new PR

My mistake. I did a clone from corporate billing instead of from main. I've removed the corporate billing item from this PR. Let me know if you need me to close this PR and resubmit a new PR instead of using this one.

**Comment by ftisiot** [comment]
Hi @sluhur, I had to make quite some effort to clean this branch. I believe, for the others, is better to start from scratch with a new PR

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
