### PR TITLE
Fixed community icon and some vale errors

### PR DESCRIPTION
**Pull request by ftisiot**
# What changed, and why it matters

Fixed the following errors

```
/Users/francescotisiot/Documents/GitHub/devportal/docs/platform/howto/manage-vpc-peering.rst:44: WARNING: Content block expected for the "note" directive; none found.
/Users/francescotisiot/Documents/GitHub/devportal/docs/platform/howto/vpc-peering-gcp.rst:4: WARNING: Title underline too short.

Set up Virtual Private Cloud (VPC) peering on Google Cloud Platform (GCP)
======================================================================
/Users/francescotisiot/Documents/GitHub/devportal/docs/products/postgresql/howto/monitor-database-with-datadog.rst:15: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/francescotisiot/Documents/GitHub/devportal/docs/products/postgresql/howto/monitor-database-with-datadog.rst:28: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/francescotisiot/Documents/GitHub/devportal/docs/products/postgresql/howto/monitor-database-with-datadog.rst:33: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

and added Community challenge icon in line with the rest of the community icons

### CODE REVIEW

**Comment by laysauchoa** [comment]
The content of challenges is different from the social media accounts. What do you think about moving this content to it is own section like we do for the **Documentation contributors** in Community? Having it is own section will allow to scale better. The two sub-lists are already squeezed in this block but there you can have a proper list of challenges and even add their own cards if you think looks better. What do you think?

**Comment by ftisiot** [comment]
Yeah, that could also work for me

**Comment by ftisiot** [comment]
moved to a separate section

**Review by laysauchoa — APPROVED** [review]
looks great! and feel free to add boxes for the challenges if you think it makes sense.

**Pull request merged**
