### PR TITLE
Cassandra: Add documentation for the Cassandra upgrade

### PR DESCRIPTION
**Pull request by rsalevsky**
# What changed, and why it matters

### CODE REVIEW

**Comment by laysauchoa** [comment]
Sorry, I mistake that this was for review so I just applied some small fix so the build could run. Feel free to reset it if does not make sense.

**Comment by lornajane** [comment]
Just a quick note that we probably need to create the landing page as well for Cassandra in order to be able to merge this, please let us know if you have a timescale in mind? We'll put something together!

**Comment by lornajane** [comment]
@rsalevsky is this PR no longer needed? It would be good to add a comment when we close a PR without merge if possible.

**Comment by rsalevsky** [comment]
@lornajane It is still needed but we (@diawarr and I) decided to have it as a help article and move the Cassandra content altogether. Just having a single article made no sense.

**Pull request closed without merging**
