### PR TITLE
redis: how to troubleshoot connection issues

### PR DESCRIPTION
**Pull request by allypascoe-aiven**
# What changed, and why it matters
Adding page for troubleshotting redis connection issues

### CODE REVIEW

**Comment by allypascoe-aiven** [comment]
Considering Tcpdump and Wireshark are the name of **tools**, I'm not sure how this is meant to be released because of the automated checks.

**Comment by harshini-rangaswamy** [comment]
@allypascoe-aiven, require any help with this pull request? The linting process is encountering issues due to 'Tcpdump' and 'Wireshark' not being recognized words. To resolve this, consider including these words in the /devportal/.github/vale/dicts/aiven.dic file. If you'd like, I'm happy to make these changes for you/

**Comment by allypascoe-aiven** [comment]
@harshini-rangaswamy thank you for letting me know, I'll have a go at adding it myself - will reach out if I get stuck :)

**Comment by allypascoe-aiven** [comment]
See https://github.com/aiven/devportal/pull/2084

**Pull request closed without merging**
