### PR TITLE
Add "Connect with Python" page to Cassandra documentation

### LINKED ISSUE #98: Cassandra connecting article
Detail how to find and use the connection details for this service

### PR DESCRIPTION
**Pull request by pparmin**
# What changed, and why it matters
> **DISCLAIMER**: this is the same approach as for #1222 

I have moved the example code which could previously only be found on our GitHub: https://github.com/aiven/aiven-examples/tree/master/cassandra/go and was mentioned in our old help article: https://help.aiven.io/en/articles/1803299-getting-started-with-aiven-for-cassandra to a separate page, as is the approach in our documentation for the other services as well.

While doing so, I also moved the old GitHub example into one code file as this improves the clarity of the example and also contains the code in only one file, as is our approach for our other services as well. I also made some surface changes to the code itself in order to improve the readability.

This partly fixes #98

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
Hi @pparmin 
Thanks a lot for this! It's almost perfect! 

However, could you please simplify the code? You can check the examples in the Kafka one https://developer.aiven.io/docs/products/kafka/howto/connect-with-python.html 

While having something executable is nice, the parameter handling is strictly not needed and I believe it's better to focus on what is needed only with the proper placeholders!

**Comment by pparmin** [comment]
Hey @ftisiot, 
Thank you for the quick review of the PR! 

I had a look at the Kafka article you linked above. Based on it, I would propose the following changes to the Cassandra article: 

```python
import ssl
from cassandra.auth import PlainTextAuthProvider
from cassandra.cluster import Cluster
from cassandra.policies import DCAwareRoundRobinPolicy

auth_provider = PlainTextAuthProvider(USER, PASSWORD)
ssl_options = {"ca_certs": CERTFILE_LOCATION, "cert_reqs": ssl.CERT_REQUIRED}
with Cluster(HOST, port=PORT, ssl_options=ssl_options, auth_provider=auth_provider, 
                    load_balancing_policy=DCAwareRoundRobinPolicy(local_dc='aiven')) as cluster:
        with cluster.connect() as session:
        # Here you can now read from or write to the database
```

This way we only present the strictly necessary information to establish a connection and cut out the overload of information. I also removed the calls to the `args` placeholders. 

What do you think?

**Comment by ftisiot** [comment]
Agreeed!

**Comment by pparmin** [comment]
I forgot to mention in the message of the last commit that I also re-arranged the order of the sections to bring it in line with our current format again (Pre-requisites --> Variables --> Code sample).

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
