### PR TITLE
Initial commit for `avn account`

### PR DESCRIPTION
**Pull request by ftisiot**
# What changed, and why it matters

Documentation for `avn account`: there are several options split in 3 files.

The `avn account authentication-method` probably needs better examples.

### CODE REVIEW

**Comment by ftisiot** [comment]
Fixed  #126

**Comment by ftisiot** [comment]
Added link

**Review by encima — APPROVED** [review]
Aside from the generic `LGTM`, this is a solid, concise overview of the functionality. You already added the link to the `concepts` page and I think it is super important that that is clear for all users; especially because we use `account` with at least 3 different meanings.

Big fan of the example use cases, in particular the explanation of their outcome.

Possibly off-topic for this PR but I cannot help but feel that this should be auto built from the code/openapi spec.

**Comment by lornajane** [comment]
Off topic but I think we can't _quite_ build this ( with the words, and examples, and everything ) from the code but we should definitely contribute some wording improvements up into the CLI at some point and then we could get closer with generated code.

Related (but still off topic) I think there's something where we should be able to produce things like https://developer.aiven.io/docs/products/postgresql/reference/list-of-advanced-params.html from somewhere in the core codebase....

**Review by lornajane — APPROVED** [review]
If it's good enough for @encima then it's good enough for me. Thanks @ftisiot :)

**Comment by lornajane** [comment]
Just going to rebase for that conflict before I merge, hold onto you hats

**Pull request merged**
