### PR TITLE
Help 118 explaining backup policies clearly

### PR DESCRIPTION
**Pull request by cybermax-008**
This article contains all the general details how Aiven takes backup for each service and its retention policy

Ports (and expands on) https://help.aiven.io/en/articles/510097-how-long-are-my-backups-stored-for

### CODE REVIEW

**Comment by laysauchoa** [comment]
@cybermax-008 I believe your branch is not update. A way to fix this is to rebase and solve the conflicts :) let me know if you need any help.

**Comment by cybermax-008** [comment]
> @cybermax-008 I believe your branch is not update. A way to fix this is to rebase and solve the conflicts :) let me know if you need any help.
Thanks for letting me know! I guess i have fixed the conflicts and rebased. Hope things are fine now!

**Comment by lornajane** [comment]
I'm rebasing this now - the current branch has a LOT of changes, I don't think 81 commits and 49 changed files is correct.

**Comment by lornajane** [comment]
7 commits and 3 changed files, and a decent changeset looks a lot better :) Bear in mind that anyone who has this branch checked out locally needs to make sure they have this new version before they make any more changes. I think we're ready for review now!

**Comment by cybermax-008** [comment]
> 7 commits and 3 changed files, and a decent changeset looks a lot better :) Bear in mind that anyone who has this branch checked out locally needs to make sure they have this new version before they make any more changes. I think we're ready for review now!

I guess i messed up the branch. thanks for the check.

**Review by laysauchoa — APPROVED** [review]
Very appreciated, looks good!!!

**Comment by TibsAtWork** [comment]
Thank you very much to @cybermax-008 for all the work on this. Apologies for it taking a while for us to get back to it.

**Pull request merged**
