### PR TITLE
Add vale easy install command

### PR DESCRIPTION
**Pull request by NotoriousPyro**
Added a quick command to get the latest Vale from tar.gz and then untar it to $HOME/bin

This is because I don't want to use brew or snap to install it, and their doco only seems to have a simple example that uses the current dir instead of tmp dirs and $HOME/bin: https://vale.sh/docs/vale-cli/installation/#github-releases

I'm not sure if this is more suitable elsewhere.

### CODE REVIEW

**Comment by NotoriousPyro** [comment]
Might be more suitable as a target in https://github.com/aiven/devportal/blob/main/Makefile

Thoughts?

**Comment by NotoriousPyro** [comment]
Might be more suitable as a target in https://github.com/aiven/devportal/blob/main/Makefile

Thoughts?

**Comment by lornajane** [comment]
I am a little nervous of encouraging people to run commands and pipe things to curl and so on. So let's definitely not hide the details away; people should be aware of what they are running. We can also link to the project installation instructions so that people always refer to the current process recommended by the project.

**Comment by NotoriousPyro** [comment]
Agreed. Will also add `-v` to `cp` to make it verbose so that people know what's being copied from where.

**Review by lornajane — APPROVED** [review]
Thanks very much!

**Pull request merged**
