### PR TITLE
Reorganized the product lists

### PR DESCRIPTION
**Pull request by harshini-rangaswamy**
# What changed, and why it matters

 Reorganized the product lists in the left navigation and documentation landing page.  The ordering is a combination of alphabetical and strategic placement. 
- The Platform section remains at the top of the list due to its importance and relevance in the product suite.
- The Apache product suite(Kafka, Flink, Cassandra). Within the Apache suite, Kafka is prioritized first as a key product from Aiven, followed by Flink and Cassandra.
- The remaining products are listed in alphabetical order.

Fixes: #1597

### CODE REVIEW

**Comment by TibsAtWork** [comment]
I'm still thinking on this (it looks strange because it's new!), but I did notice that the Apache items are in reverse alphabetical order

**Comment by harshini-rangaswamy** [comment]
> I'm still thinking on this (it looks strange because it's new!), but I did notice that the Apache items are in reverse alphabetical order
The Apache product suite(Kafka, Flink, Cassandra). Within the Apache suite, Kafka is prioritized first as a key product from Aiven, followed by Flink and Cassandra.

**Comment by harshini-rangaswamy** [comment]
> I'm still thinking on this (it looks strange because it's new!), but I did notice that the Apache items are in reverse alphabetical order
I don't think placing Platform between the products makes a lot of sense. It's better at the top. 
image
I could probably re-order the Apache suite: 
 - Apache Cassandra
 - Apache Flink
 - Apache Kafka 
 
 However, I feel Apache Kafka before Flink is more logical.

**Comment by TibsAtWork** [comment]
I think that your proposal is definitely an improvement, and worth adopting.
I understand your point on the Apache products, and it's a short enough list I don't think it's going to cause any problems.

**Review by TibsAtWork — APPROVED** [review]
It's definitely much better than what we had before. And it seems to make sense in the page with the product cards as well. Thanks

**Pull request merged**
