### PR TITLE
Adding instructions on topic creation for kafka

### PR DESCRIPTION
**Pull request by frconil**
# What changed, and why it matters

Adding a small article on how to create kafka topics using either the Aiven console or Aiven client.

### CODE REVIEW

**Comment by ftisiot** [comment]
@frconil Thanks for your contribution, some good content we need! 

I've rebased and changed the wording slightly, could you please check it's ok before we merge?

**Comment by frconil** [comment]
LGTM! That said, should we add the ® to every instance of Apache Kafka?

**Comment by frconil** [comment]
Same here @ftisiot , i made the changes requested plus the decoupling from the docs and CLI docs.

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
