### PR TITLE
kafka gcs sink terraform recipe

### PR DESCRIPTION
**Pull request by sluhur**
# What changed, and why it matters

Resolves https://github.com/aiven/devportal/issues/1053

### CODE REVIEW

**Comment by lornajane** [comment]
Just checking in whether we're waiting for review or author updates on this one. @dewan-ahmed  or @sluhur , what's the next step?

**Comment by dewan-ahmed** [comment]
Hi @sluhur this morning I tested the setup again.

Good news: the resources get created fine (after the usual tweaking with GCP credentials json).

Bad news: Once I produce some messages to the Kafka source topic, the GCS connector task fails with the following stacktrace:

`org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:338)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
	... 13 more`

I tried adding "schemas.enable": "false" to the connector configuration but still see the same error. Would you be able to test this setup? Let me know if you'd like to hop on a call to discuss or troubleshoot. Thanks.

**Comment by dewan-ahmed** [comment]
Hi @sluhur I converted this PR to a draft for now. Let me know if you were able to get the GCS connector task working and see the data on Google Cloud Storage. I'm also happy to jump on a call and work on this together.

**Comment by dewan-ahmed** [comment]
Hi @sluhur I'll be deleting the branch ``kafka_gcs_sink_connector`` so please make a backup of the unmerged commits, if necessary. Thanks.

**Pull request closed without merging**
