### PR TITLE
Migration MySQL backups

### PR DESCRIPTION
**Pull request by laysauchoa**
Fixes: #662
Link: https://help.aiven.io/en/articles/5199859-mysql-backups

### CODE REVIEW

**Comment by laysauchoa** [comment]
Waiting for a feedback about the MySQL backup plans info.

**Comment by laysauchoa** [comment]
Once [PR](https://github.com/aiven/devportal/pull/751/files) is merged, we can link this article to there.

**Comment by TibsAtWork** [comment]
Please undo my "english" edits if they feel bad to you.

Should we copy the `You may modify the backup time configuration option ...` text from that new article?
This information wasn't in the original help text that you're migrating. It feels like something that probably does belong here.

(I'm uncomfortable with duplicating information, but I think that's acceptable, and this article does go a bit deeper than the "general" one)

**Comment by laysauchoa** [comment]
> Please undo my "english" edits if they feel bad to you.
> 
> Should we copy the `You may modify the backup time configuration option ...` text from that new article? This information wasn't in the original help text that you're migrating. It feels like something that probably does belong here.
> 
> (I'm uncomfortable with duplicating information, but I think that's acceptable, and this article does go a bit deeper than the "general" one)

they are good @TibsAtWork! we can merge this PR, what do you think?

**Comment by laysauchoa** [comment]
sorry, I may have lost your comment. I added the changes now @TibsAtWork Thank you!

**Review by TibsAtWork — APPROVED** [review]
Looks good to me - much better than the original.

**Pull request merged**
