### PR TITLE
Migrate article: Error: Private only access to service ports cannot b…

### LINKED ISSUE #1060: Migrate article: Error: Private only access to service ports cannot be enabled for the service's network
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5616082

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

### PR DESCRIPTION
**Pull request by sluhur**
Fix #1060 
# What changed, and why it matters

### CODE REVIEW

**Review by ftisiot — COMMENTED** [review]
Hi @sluhur ,
Thanks for this, can you please review the warnings? Also, isn't this about Terraform? shouldn't we put it under the Terraform subtree?

**Comment by ftisiot** [comment]
Hi @sluhur, did you verify that the issue is still there?
Tagging @dewan-ahmed since it's part of terraform

**Comment by lornajane** [comment]
It's great that we have the full error message included so that it can be found with search! Could we however use more constructive language for the title? A title about an error and what you can't do does not align with our style guide (don't hide anything, but the article title could be about private access for VPCs, for example).

**Comment by dewan-ahmed** [comment]
Thanks @sluhur for this contribution.

I echo what @lornajane mentioned. HowTo articles have a format "VERB <DO SOMETHING>". This article seems more like an FYI that says do not use "private_access" option in Terraform when you're using VPC or else you'll find the mentioned error.

Since this article. doesn't show the user how to perform a task, I suggest "Reference > Troubleshooting" to be a potential home for this article. What do you think @lornajane? Potential article title "Private access error when using VPC".

@sluhur do you have the Terraform manifest to perform this action (a service, a project VPC, a peering, with private_access configured for the service)? This will save me time when validating the PR. Thanks.

**Comment by sluhur** [comment]
> this action (a service, a project VPC, a peering, with private_access configured for the service)? This will save me time when validating the PR. Thanks.

Hi @dewan-ahmed ,

apologize for the delay. This is the example of the terraform recipe

###A single-node Redis service

resource "aiven_redis" "single-node-aiven-redis" {
  project                 = var.project_name
  cloud_name              = "google-northamerica-northeast1"
  plan                    = "startup-4"
  service_name            = "gcp-single-node-redis1-simon"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"

  redis_user_config {
    redis_maxmemory_policy = "allkeys-random"

    private_access {
      redis = true
    }
  }
}

##As usual, just create this with terraform apply -var-file=var-values.tfvars

**Review by dewan-ahmed — APPROVED** [review]
Thanks for this contribution @sluhur

**Pull request merged**
