### PR TITLE
Improvements for the getting started guide for Redis

### PR DESCRIPTION
**Pull request by pparmin**
# What changed, and why it matters
Fixes: [#698](https://github.com/aiven/devportal/issues/698)

I have updated the [Redis getting started guide](https://developer.aiven.io/docs/products/redis/get-started.html) with two exemplary sections that guide the user through service creation, using both the web console and the CLI. As suggested by @dewan-ahmed, I have used the [Flink getting started guide](https://developer.aiven.io/docs/products/flink/getting-started.html) as inspiration. 

## Minor updates
I have additionally renamed the file from `get-started.rst` to `getting-started.rst` to provide a more consistent naming of the files across the board. 
This required the update of the file name in a number of other files to avoid broken links.

### CODE REVIEW

**Comment by pparmin** [comment]
Thank you @laysauchoa. In what way have title changes been made by my PR? Or did I misunderstand your comment? 

In any case, would it be preferable to revert the renaming of the file, considering that "Get started..." is the title, or does it not really matter?

**Comment by laysauchoa** [comment]
I just added here for awareness since both PRs are modifying the same file :)

**Comment by laysauchoa** [comment]
Although, there is some different ways in how to explain the creation of the service. For me, it seems reasonable to reuse some of the content written. I like how it was done for the ClickHouse, recently adde by @anelook https://developer.aiven.io/docs/products/clickhouse/getting-started.html

I'd suggest that we just redirect the user to the general way of creating a service rather than explaining it again. My main reason is:

* reuse content
* avoid to get outdated fast

So I'd prefer to keep it as it was or similar to this one and just separate in two sessions from console and from the command line.

**Comment by laysauchoa** [comment]
@dewan-ahmed this is good to merge imo. let me know if it is okay from your side. we can continue the more general topics in another issue, wdyt?

**Review by laysauchoa — APPROVED** [review]
Thanks for your contribution. The PR looks good to me 💯  @pparmin

**Comment by laysauchoa** [comment]
I just want to clarify that undo the change of the file as it causes changes in the URL, and it could be a problem for redirections.

**Comment by dewan-ahmed** [comment]
Thanks @pparmin for the PR and @laysauchoa for the review

LGTM from my end as well.

**Comment by pparmin** [comment]
Thank you @dewan-ahmed and @laysauchoa for your active help on this one :)

**Pull request merged**
