### PR TITLE
Add feedback form and store results in pg

### PR DESCRIPTION
**Pull request by aiven-hh**
Setup:

* Get service url from Aiven console without `sslmode=require`, example: `postgres://avnadmin:pass@service-name-project-name.aivencloud.com:12691/defaultdb`
* Add service url to environment with key `PG_URL` (for Netlify also)
* Download `ca.pem`CA certificate from Aiven console and save it as `netlify/functions/ca.pem`, this is currently the CA cert for dev instance
* Run `make create-feedback-table` to create the table in PG.

Implements #74

### CODE REVIEW

**Comment by hab-anka** [comment]
Can we please change the default text? These sound a bit formal and "document" is not super accurate ....

Did you find this document useful? > Did you find this useful?

What did you think about the document? > Anything specific you want to share?

Thank you for your feedback. > Thanks for your opinion!

**Comment by lornajane** [comment]
In the preview setup, I can see that the forms work, but the functions aren't in place to fire yet so the data does not arrive in the database. Could you please add:
 - pick up the URL of the page and pass it with the form? This would let us build other integrations straight off the forms data/trigger, not just from the function/database end of things. And I guess this data is available when clicking.
 - add/enable (or explain to me if it's there and I didn't see it) any anti-spam measures that we can use here.

**Comment by lornajane** [comment]
Note that the database URL has been added to both the netlify environment variables and to the github action secrets (why does GitHub need it?), and that the cert has been updated in the repo to match.

**Review by lornajane — CHANGES_REQUESTED** [review]
Need to pick up the page URL earlier in the process, and add some anti-spam (see more detailed comment on the PR). Thanks for already updating the wording we requested :)

**Comment by aiven-hh** [comment]
Github does not need the secret, my comment was a bit unclear. I meant that wherever you run the `make create-feedback-table` should have the variable set (locally).

Netlify has Akismet filtering on by default (based on the input text) but do you want additional filtering like honeypot field or recaptcha (https://docs.netlify.com/forms/spam-filters/).

You can see the page url in netlify submissions already if you use the download as CSV functionality. The web ui does not show it by default.

**Comment by lornajane** [comment]
A honeypot would seem like a good idea (I'm not an expert though), let's add one.

**Comment by lornajane** [comment]
Thanks for the update on the postgres settings - I created the table and removed the secret from the repo since we don't need it over here. It's all starting to make sense :)

**Comment by aiven-hh** [comment]
I have added the honeypot field and netlify seemed to notice it saying `Extra spam prevention enabled via honeypot field.` in form submissions.

Also returning the page url. I don't think url needs to be added to the form. Netlify takes it from referrer header and adds it to the data passed to the function and I would guess to any other integrations as it is available in netlify form submissions. If it is not available to other integrations for some reason then I would add it.

**Comment by lornajane** [comment]
This is looking really good, thanks for advising and adding the honeypot. I don't know if it will help but at least we tried.

We will be reviewing the comments from time to time, but we can't identify the user or respond quickly, and I would like to make that clear from the form. After the text "Anything specific you want to share?" could we therefore add "(Please don't share any personal details here. If you need a response, support@aiven.io is the best way to reach us)" to try to help users understand what they're interacting with.

**Comment by lornajane** [comment]
@aiven-hh any danger you can update the wording on this? I'm keen to have it in action!

**Comment by aiven-hh** [comment]
Sorry I didn't notice the previous comment. I added the text with the same font right after the old one, tell me if it needs any changes.

**Review by lornajane — APPROVED** [review]
This looks good to me, thanks very much!

**Pull request merged**
