### PR TITLE
Add GCP cloud logging integration article

### PR DESCRIPTION
**Pull request by staceysalamon-aiven**
# What changed, and why it matters
Migrated the Google Cloud Logging integration content over from the old [help center article](https://github.com/aiven/aiven-intercom-docs-archive/blob/1d565125474ab6049a4c240265dbcb3a8dc6d3f5/archive/4209837/4209837-sending-service-logs-to-google-cloud-logging.rst).

### CODE REVIEW

**Comment by angelinekwan** [comment]
Build error in Cloudflare Pages due to this https://github.com/aiven/devportal/actions/runs/4225032507/jobs/7336762310#step:5:1321

**Comment by staceysalamon-aiven** [comment]
> Build error in Cloudflare Pages due to this https://github.com/aiven/devportal/actions/runs/4225032507/jobs/7336762310#step:5:1321

Thanks for pointing that out! I don't understand why that syntax is not working in that one place only and is working everywhere else, but it's working now. 👍

**Comment by wojcik-dorota** [comment]
> 

For code blocks, I use `.. code-block:: <programming language>`. That way I get no errors. In line 60, you have no language defined.

**Comment by staceysalamon-aiven** [comment]
> > 
> 
> For code blocks, I use `.. code-block:: <programming language>`. That way I get no errors. In line 60, you have no language defined. Also, there was a recommendation to switch from `code` to `code-block` in the devportal slack channel a while ago.

Removing the language is what made the errors stop happening. Otherwise, it kept flagging line 60 even though the formatting is the same elsewhere int his and other articles.

Could you please add the formatting to the style guide perhaps (or somewhere in the contributing file)? It's easy to miss things in noisy Slack channels and they are not visible to everyone contributing.

**Comment by wojcik-dorota** [comment]
> Removing the language is what made the errors stop happening.

This is a general Sphinx syntax rule - https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block. No need to add it to the contributing file from my perspective. Please update the contributing file with whatever you find necessary.

**Comment by staceysalamon-aiven** [comment]
@wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323

**Comment by wojcik-dorota** [comment]
> 

yeah, I can see that. Sorry, no clue what's the reason for this one this time.

**Comment by harshini-rangaswamy** [comment]
> @wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323

Using just `..code::` didn't work? I can take a quick look.

**Comment by staceysalamon-aiven** [comment]
> > @wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323
> 
> Using just `..code::` didn't work? I can take a quick look.

Yes, as you can see in the convo above that did work when there was no language specified, but it was then changed to code-block per the suggestion.

**Comment by staceysalamon-aiven** [comment]
If we can't figure it out today I will just go back to the format that worked so we can get this published and not waste too much time on this.

**Comment by harshini-rangaswamy** [comment]
> Details



> > > @wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323
> > 
> > 
> > Using just `..code::` didn't work? I can take a quick look.
> 
> Yes, as you can see in the convo above that did work when there was no language specified, but it was then changed to code-block per the suggestion.



> > > @wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323
> > 
> > 
> > Using just `..code::` didn't work? I can take a quick look.
> 
> Yes, as you can see in the convo above that did work when there was no language specified, but it was then changed to code-block per the suggestion.

I have noticed that `. code-block:: <programming language>` is mostly for syntax highlight and works well for the 1st occurrence in the docs, and subsequent occurrence throws an error. I would just use `..code::` or `code-block` without the programming language, and it has worked for me.

**Comment by staceysalamon-aiven** [comment]
> > Details
> 
> > > > @wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323
> > > 
> > > 
> > > Using just `..code::` didn't work? I can take a quick look.
> > 
> > 
> > Yes, as you can see in the convo above that did work when there was no language specified, but it was then changed to code-block per the suggestion.
> 
> > > > @wojcik-dorota Same issue after reformatting to code-block: https://github.com/aiven/devportal/actions/runs/4280441367/jobs/7452215064#step:5:1323
> > > 
> > > 
> > > Using just `..code::` didn't work? I can take a quick look.
> > 
> > 
> > Yes, as you can see in the convo above that did work when there was no language specified, but it was then changed to code-block per the suggestion.
> 
> I have noticed that `. code-block:: <programming language>` is mostly for syntax highlight and works well for the 1st occurrence in the docs (or single occurrence in the docs), and subsequent occurrence throws an error. I would just use `..code::` or `code-block` without the programming language, and it has worked for me.

Strange, because this is actually the first occurrence that is throwing the error. But, I will go back to the syntax that worked. 

If one of you then wouldn't mind approving quickly so we can get the updated link to Marketing, that'd be great! @wojcik-dorota @harshini-rangaswamy

**Pull request merged**
