### PR TITLE
Connect nosqlbench cassandra

### PR DESCRIPTION
**Pull request by fmanimali**
# What changed, and why it matters

This PR is for a new article on how-to use nosqlbench to connect, load and stress test cassandra service.
Please review and let me know what I missed.

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
Hi @fmanimali thanks for the contribution!

Can you please check the warnings and errors in the build? Most of them will be resolved by adding the missing words to the dictionary in `.github/vale/dics/aiven.dic` and fixing the spelling

**Comment by fmanimali** [comment]
It should be ready to be published. Thanks for reviewing.

**Comment by ftisiot** [comment]
Thanks @fmanimali, I changed slightly the formatting, could you please check if it's accurate?

**Comment by ftisiot** [comment]
I also removed the last sentence about the new tool to count the data, since I'm expecting a dedicated article from you in the future. Once we have that, we can link from this article

**Comment by fmanimali** [comment]
Looks good to me. Thank you for your review @ftisiot

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
