### PR TITLE
Remove default sort by source. Add boost for devportal articles.

### PR DESCRIPTION
**Pull request by ak-aiven**
Modify the search functionality so help articles are sorted better by relevancy

### CODE REVIEW

**Comment by ak-aiven** [comment]
https://github.com/aiven/devportal/issues/895

**Review by encima — APPROVED** [review]
Thanks for picking this up; much better!

**Comment by laysauchoa** [comment]
Hi @encima and @ak-aiven, were you able to test it locally? I was not able to, so this is why I am asking. On the way, I found something else wrong. 


Instructions: https://github.com/aiven/devportal/blob/main/SEARCH.md instructions

**Comment by encima** [comment]
I was able to test in the deployed preview. The index itself does not need to change, though, only how it is queried is changing here

**Pull request merged**
