### PR TITLE
Added Cassandra source and sink connectors

### LINKED ISSUE #1156: Kafka Connect Cassandra source/sink
# What should we add to our content collections?

(more information is useful here! Were you trying to do something particular?)

Migrate https://help.aiven.io/en/articles/3281827-setting-up-cassandra-sink-connector-for-kafka and write article about source cassandra connector

# Is this something you would work on yourself?

[X] I plan to open a pull request for this

### PR DESCRIPTION
**Pull request by ftisiot**
# What changed, and why it matters

Added Cassandra source connector 
Migrated Cassandra sink connector  https://help.aiven.io/en/articles/3281827-setting-up-cassandra-sink-connector-for-kafka

Fixes #1156

The Cassandra sink connector currently fails due to a [problem in the connector itself](https://github.com/lensesio/stream-reactor/issues/760), waiting for a fix

### CODE REVIEW

**Comment by lornajane** [comment]
So can we test this if there's a bug in the connector? I'm not clear if we should be crowdsourcing reviews or what

**Comment by ftisiot** [comment]
I believe we can review one of the connectors, the worst part IMHO is that we have a non working connector available since some time

**Comment by dewan-ahmed** [comment]
The [failed connector GitHub issue](https://github.com/lensesio/stream-reactor/issues/760) mentions about a fix in the next release date but so far, there's no ETA on the release date. If we prioritize the migration over a failing connector that is not an Aiven issue, my suggestion will be to add a ⚠️ note with a link to the [failed connector GitHub issue](https://github.com/lensesio/stream-reactor/issues/760).

**Review by mparikhaiven — CHANGES_REQUESTED** [review]

**Comment by ftisiot** [comment]
Thanks @mparikhaiven, ready for another go!

**Review by mparikhaiven — APPROVED** [review]
Changes LGTM, thnx @ftisiot !

**Pull request merged**
