### PR TITLE
add lib to run `page_status.py`

### PR DESCRIPTION
**Pull request by laysauchoa**
Add required lib to be able
to run the `page_stats.py` locally

Fixes: https://github.com/aiven/devportal/issues/598

### CODE REVIEW

**Comment by laysauchoa** [comment]
related to: https://github.com/aiven/devportal/pull/581

**Comment by lornajane** [comment]
Does pip have a concept of development requirements? I intentionally omitted this from the requirements because if it can't be installed, the site still works. It really isn't a requirement, and we would want the build to fail be of a problem with it

**Comment by laysauchoa** [comment]
normally there is a dev requirements where those dependencies can be placed like test dependencies etc that the user does not to know if they want to use the library. I see that there are other libraries there related to this script, for example: ``BeautifulSoup`` but it is used in indexing scripts as well. I think I need help to divide which dependencies would go to this file and which dependencies would stay in the ``requirements.txt``.

Should we make sure that running dev requirements would install both dependencies? or should they be isolated?

Would be a good idea to include in the README that there is specific dependencies for development? or more info about the scripts?

**Comment by lornajane** [comment]
I think the separate file and a `README` section would be helpful if we want to formalise the inclusion of the script in the project. I didn't do a whole lot with it because it is temporary, probably only you and I will run this to provide numbers on the migration, then we can remove the script when the knowledgebase is decommissioned.

I suggest we add a section to explain that we have this short-term need for migration metrics, and that the new requirements file and the script itself are needed. There's also a feature that is worth mentioning, set the `INDEX_DEBUG` variable to get the detailed output of the pages (similar to what the indexing script outputs). Sometimes, the extra info is useful.

**Review by lornajane — COMMENTED** [review]
I think this needs a README update to go with it, you are really right that it probably should not just be a script by itself.

**Comment by laysauchoa** [comment]
would that be a good solution for this script (even if temporary)?

**Review by lornajane — APPROVED** [review]
Thanks for taking the time on this!

**Pull request merged**
