### PR TITLE
Grafana recipe - part of Terraform Cookbook Epic

### PR DESCRIPTION
**Pull request by dewan-ahmed**
# What changed, and why it matters

Resolves https://github.com/aiven/devportal/issues/873

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
This is currently failing for me with 

```
│ Error: Reference to undeclared input variable
│
│   on services.tf line 5, in resource "aiven_pg" "demo-pg":
│    5:   service_name           = join("-", [var.service_name_prefix, "postgres"])
│
│ An input variable with the name "service_name_prefix" has not been declared. This variable can be declared with a variable "service_name_prefix" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│
│   on services.tf line 15, in resource "aiven_grafana" "demo-grafana":
│   15:   service_name            = join("-", [var.service_name_prefix, "grafana"])
│
│ An input variable with the name "service_name_prefix" has not been declared. This variable can be declared with a variable "service_name_prefix" {} block.
```

On top of it, please check the warnings, moving away from **aiven_pg** to `aiven_pg` will eliminate them

**Comment by dewan-ahmed** [comment]
Thanks @ftisiot for the review.

The failure happens due to the same reason mentioned [here](https://github.com/aiven/devportal/pull/886#issuecomment-1152333863). We don't include the common files that are needed to execute the recipes to avoid duplication. But thanks to your comment, I'm starting to include tips like this in these recipes:

.. Tip::

    Be sure to check out the :doc:`getting started guide <../../get-started>` to learn about the common files required to execute the following recipe. For example, you'll need to declare the variables for ``project_name``, ``api_token``, and ``service_name_prefix``.

[terraform-exec-logs.zip](https://github.com/aiven/devportal/files/8920255/terraform-exec-logs.zip)

Regarding the warning with `aiven_pg`, are you using the latest version of the provider (3.1)? I've attached a complete log of terraform plan/apply here. I couldn't see that warning. @mhoffm-aiven pls let me know if I'm missing something with that warning. Thanks.

**Comment by ftisiot** [comment]
Warning: The integration doesn't seem to work. I don't see any dashboard in grafana.
Maybe this is because you need to push the metrics to a time-series database first?

**Comment by dewan-ahmed** [comment]
Hi @ftisiot I have included M3DB as the time-series database per your suggestion. From what I see, the three services and three service integrations are created. Would you be able to test one more time if you see a dashboard in Grafana?

I've made changes to some text and the diagram. Please let me know if the new diagram makes sense and if any revision is needed. Thanks.

**Comment by dewan-ahmed** [comment]
Hi @ftisiot, thanks for the review and changes. I tested the edited Terraform code and the services & service integrations are created on the console. 

The only concern I have is why the deploy preview is pointing to https://deploy-preview-949--developer-aiven-io-preview.netlify.app/docs/products/grafana/reference/advanced-params instead of https://deploy-preview-949--developer-aiven-io-preview.netlify.app/docs/tools/terraform/reference/cookbook/grafana-m3db-postgresql-recipe.html

But I checked the two changes file on this branch - _toc.yml and docs/tools/terraform/reference/cookbook/grafana-m3db-postgresql-recipe.rst which look good to me. 

If you feel that the deploy preview issue is not something to worry too much, the PR is good from my end.

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
