### PR TITLE
Migrate maintenance downtime

### PR DESCRIPTION
**Pull request by sluhur**
# What changed, and why it matters

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
This is the same as #1285, please include in a PR only the changes relevant to that one

Thanks

**Comment by sluhur** [comment]
> This is the same as #1285, please include in a PR only the changes relevant to that one
> 
> Thanks

Same mistake. I've removed the corporate billing item from this PR. Let me know if you need me to close this PR and resubmit a new PR instead of using this one.

**Review by ftisiot — CHANGES_REQUESTED** [review]
Hi @sluhur can you please check the files included in this PR? I see an extra entry in the dic and an image

I would just take the needed extra content and start a new PR starting from main?

**Comment by sluhur** [comment]
I'm closing this one as I have created another PR https://github.com/aiven/devportal/pull/1326

**Pull request closed without merging**
