### PR TITLE
feat: add twitter card

### PR DESCRIPTION
**Pull request by turq84**
# Task: Add social tags [developer.aiven.io]
developer.aiven.io pages are lacking OpenGraph Tags and Twitter Cards.

## OpenGraph Tags
Make sure your pages have Open Graph tags if you want them to look good in social feeds when shared.
Please note that URLs inside OG tags must be absolute and utilize the http:// or https:// protocols.

You can find more information on the Open Graph protocol here.

## Twitter Cards
If you want your pages to look good in the Twitter feed when shared, you should implement the Twitter card tags available.
Please note that URLs inside Twitter cards must be absolute and utilize the http:// or https:// protocols.
You can find more information about Twitter cards here.

# Solution
Add opengraph Sphix package (`sphinxext-opengraph`) and Twitter card metadata to the `base.html` file. 

## Note
For the Twitter metadata, I wasn't about to get the dynamic description for each page. I looked at the base template and I thought adding `{{ description }}` to the Twitter metadata tag would solve the issue. However, the content returned empty on the web page. The current description in place is from the home page: "What can we help you with today? (Looking for the previous documentation? Visit Aiven Help or use the search above.) Explore: Learn about the Aiven platform icon-postgres PostgreSQL Powerful relation...". 

It's a general description that, I think, could apply to all page links. The only thing not dynamic is the page description.

If you have any insights into having a more dynamic page description, feel free to share them.

Preview URL: https://deploy-preview-196--developer-aiven-io-preview.netlify.app/

### CODE REVIEW

**Comment by lornajane** [comment]
How does this relate to #191 ? Perhaps we could combine them, they seem to overlap.

**Comment by turq84** [comment]
> How does this relate to #191 ? Perhaps we could combine them, they seem to overlap.

Ah, I didn't know this. I was given the assignment directly from Olga in Slack. I'll look into it on Monday.

**Comment by turq84** [comment]
The PR has been updated. Since Heikki already has a solution in place for the OpenGraph issue ([PR 191](https://github.com/aiven/devportal/pull/191)), I removed the `sphinxext-opengraph` package and kept the Twitter tags.

**Comment by lornajane** [comment]
Thanks! I'm sorry about the crossed wires, I'm trying to sort out our internal process so we don't cause this again.

Would it be possible to include an image with the twitter card?

**Comment by lornajane** [comment]
Ohhh, I think the twitter card will pick up the og images, I'm going to rebase this branch onto `main` now so that it picks up the changes already merged.

**Comment by turq84** [comment]
The og image may have worked, but it was no problem to go ahead and add that image path to the Twitter image meta tag. I used the same image path as Heikki for his og solution.

**Comment by lornajane** [comment]
I tried previewing the twitter card on the preview of this PR and it doesn't seem to pick up the image. Does `twitter:image` need a full URL rather than a relative path, do you know?

**Comment by turq84** [comment]
I have just updated the image path to include the URL. I've also found this handy Tweet preview tool from Twitter. According to this, the image is now present. https://cards-dev.twitter.com/validator

Thanks for your help and patience, Lorna!

**Review by lornajane — APPROVED** [review]
Yes! Thank you :)

**Pull request merged**
