### PR TITLE
How to enable Aiven password

### PR DESCRIPTION
**Pull request by laysauchoa**
This is needed if the user wants to authenticate and log in directly without using any 3rd parties by using Aiven username and password.

fixes:https://github.com/aiven/devportal/issues/677

### CODE REVIEW

**Comment by lornajane** [comment]
I would recommend that we instead advise users to use a token to log in with CLI

**Comment by laysauchoa** [comment]
Thanks, I'll clarify the use of this feature first.

**Comment by TibsAtWork** [comment]
Yes, I was thinking that was something important to talk about. And I'd already written "Discuss pros and cons of using password vs token." in the outline to remind me.

**Comment by laysauchoa** [comment]
I've added a note on the cli tools article about it and focused on the case that the user wants to authenticate and log in directly without using any 3rd parties by using Aiven username and password. Thanks again!

**Review by TibsAtWork — APPROVED** [review]
Thank you for sorting this out.

**Pull request merged**
