### PR TITLE
Feat/darkmode

### PR DESCRIPTION
**Pull request by turq84**
# Problem
The code-formatted font in titles is difficult to read - there is not enough contrast between background and font color.

There was an issue opened in the past #141 reporting same issue. The issue was fixed for light mode, however stayed in the dark mode.

Dark mode is applied automatically if a user sets "Dark" appearance in Mac settings.
Tested in Safari, Chrome and Firefox on Mac - applicable to all browsers.

Issue: https://github.com/aiven/devportal/issues/308

# Solution
Update the dark theme in the CSS file so the correct color is shown when users are in dark mode.

Preview URL: https://deploy-preview-309--developer-aiven-io-preview.netlify.app/docs/tools/cli/account.html

### CODE REVIEW

**Comment by lornajane** [comment]
@anelook Does this fit what you had in mind?

**Comment by anelook** [comment]
Yes, I can read it now without any efforts! Thank you, the change looks great

**Review by anelook — APPROVED** [review]
Looks good to me. I feel a bit uncomfortable about using '!important', but I see that this is a common pattern in this css file.

**Comment by lornajane** [comment]
Thank you @turq84 :)

**Pull request merged**
