### PR TITLE
migrate azure AD article for SAML

### PR DESCRIPTION
**Pull request by encima**
# What changed, and why it matters

Migrate Azure AD article. Format to match other SAML articles (with changes to existing article as well). Remove screenshots and add context to steps to make it clearer without the need for images

Addresses #810

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
@encima could you please check the warnings?

Most of them can be solved by adding `Azure` in the `.github/vale/styles/capitalization_headings.yml` file :)

**Comment by encima** [comment]
> @encima could you please check the warnings?
> 
> Most of them can be solved by adding `Azure` in the `.github/vale/styles/capitalization_headings.yml` file :)

Should Azure be added or should I change the reference to `Microsoft Azure`?

**Comment by ftisiot** [comment]
Good question... @TibsAtWork @jlprat opinions? Should we reference to Azure as `Azure` or `Microsoft Azure`?

**Comment by jlprat** [comment]
What I understand after reading their page is that we need to use `Microsoft Azure`.

https://www.microsoft.com/en-us/legal/intellectualproperty/Trademarks/

**Comment by encima** [comment]
> What I understand after reading their page is that we need to use `Microsoft Azure`.
> 
> https://www.microsoft.com/en-us/legal/intellectualproperty/Trademarks/

Odd, because they call it `AAD` (Azure Active Directory) in most of their marketing... 🤔

**Comment by ftisiot** [comment]
Hi @encima, fixed a bit the formatting, can you please scan it to check everything seems still ok? Then we're ready to merge!

**Comment by encima** [comment]
Thank you for doing it, my eyes would have missed the numbering things!

**Review by ftisiot — APPROVED** [review]
LGTM!

**Pull request merged**
