### PR TITLE
Add support details page

### PR DESCRIPTION
**Pull request by FloorD**
Closes Migrate article: Aiven support details #797

### CODE REVIEW

**Comment by lornajane** [comment]
@FloorD Assigning back to you to check the build errors so that someone can review (but shout if you need a hand!). The broken link is the one on the main page, check this on your local setup?

**Comment by laysauchoa** [comment]
Hi, do you need help to fix the build? also, are you able to run it locally? let me know if I can help :)

**Comment by lornajane** [comment]
Rebased to resolve the navigation conflict BUT I don't think that "community" is the right place for the support details. This could be a top-level platform section link perhaps? I'd also consider adding it at the bottom of the main page or something like that so people can find the info....

**Comment by lornajane** [comment]
We don't need this, the support pages have moved to https://aiven.io/support-services so the page no longer needs migrating.

**Pull request closed without merging**
