### PR TITLE
Add workflows to index pages

### PR DESCRIPTION
**Pull request by aiven-hh**
Add workflows to index devportal pages on changes to main and help center pages daily on schedule. Requires `ES_URL` to be added to repository secrets.

### CODE REVIEW

**Comment by gskhan** [comment]
@lornajane can you please add the secret? Most important, we are still not using prod ES but the sandbox

**Comment by lornajane** [comment]
Quick update from security that we are OK to add the repo secrets for this, I'll proceed.

**Comment by lornajane** [comment]
How can I see this workflow running? I've added the environment variable as a repo secret and for the devportal deploy - but at least the devportal version won't/shouldn't index unless we're pushing to main. Do I test by adding the branch name of this branch temporarily to see it build? And why aren't the cron workflows running?

**Comment by aiven-hh** [comment]
Also I couldn't really test these myself either but I tried to keep them as simple as possible and hope for the best. They just install deps and run single make command each.

**Comment by lornajane** [comment]
I created the index and pushed a temporary commit to cause the actions to run on this branch and check things work as we expected. These completed successfully so I think we can move forward with this.

**Review by lornajane — APPROVED** [review]
Triggering the actions does produce content in the index

**Pull request merged**
