### PR TITLE
Update site-preview.png

### PR DESCRIPTION
**Pull request by Hemant-Mulchandani**
# What changed, and why it matters

Update site-preview.png image #910
Site-preview image updated and Height and Width Dimensions are kept exactly the same as before i.e. 1200*630 px.

### CODE REVIEW

**Comment by ftisiot** [comment]
Hi! Thanks for the PR! Could we have an image which is consistent with the previous one, without the top bar and the "Fork me on GitHub" message? 
This way also the content in the image will be more readable
Thanks!

**Comment by Hemant-Mulchandani** [comment]
Yeah sure, I'm on it.

**Comment by Hemant-Mulchandani** [comment]
Update site-preview.png image #910

Fixes: 
Now image does have that top bar and the "Fork me on GitHub" message.

Also, to keep the image distortion-free and at the same time in the exact dimension of 1200*630 px, I had to add transparent background to it. Hope it works for you..!!

Thanks!!

**Review by ftisiot — APPROVED** [review]
LGTM, thanks for the contribution!

**Review by ftisiot — CHANGES_REQUESTED** [review]
Sorry, I didn't notice it properly that there are transparent backgrounds at the borders, in the original image it's full with content

**Comment by Hemant-Mulchandani** [comment]
Update site-preview.png image #910

Fixes : 
As requested transparent backgrounds around the borders are now removed.
Thanks!

**Review by ftisiot — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request merged**
