### PR TITLE
initial set of `avn service` docs

### PR DESCRIPTION
**Pull request by ftisiot**
Initial set of `avn service` docs

### CODE REVIEW

**Comment by ftisiot** [comment]
Solve #219 #220 #221 #222 #223 #224 #225 #226 #227 #233 #234 #257 #259

**Comment by ftisiot** [comment]
Hi @anelook and @lornajane, the `avn service` is our big monster, I would like an initial feedback on the current content and structure. Is it too much for a page? should we divide it better?
Thanks!

**Comment by lornajane** [comment]
(sorry I pressed the wrong button there!)

This is definitely a huge task, and of course the sooner we start the sooner it'll be done, so I'm impressed already!

Are you intending to get all of `avn service *` into one pull request? For `avn account` I grouped commands together rather than having purely an alphabetical list, in case people wanted to do a thing that they didn't already know the command name for.

What are you using as the basis for when to go into a subpage or not? I think we might need to do more subpages for this command that has so much at the top level that the page is really, really long.

**Comment by ftisiot** [comment]
Are you intending to get all of `avn service *` into one pull request? Nope, I started documenting... and added a bit too much in one go :D

As of now I created a subpage only when there were multiple subcommands (`connector` is the example) but I agree I'll subdivide the content per area, for example, all the `avn service acl*` will go into a separate file.

**Comment by ftisiot** [comment]
Rebased! Should be ready for the final check before merging into main

**Comment by lornajane** [comment]
Replaced by #332

**Pull request closed without merging**
