### PR TITLE
K8s operator tweaks

### PR DESCRIPTION
**Pull request by kevinbowman-aiven**
# What changed, and why it matters

A couple of additions to the Kubernetes operator docs, from some friction I had when trying it out in GCP kubernetes engine.

### CODE REVIEW

**Comment by dewan-ahmed** [comment]
Hi @kevinbowman-aiven thanks for this clarification. I validated that on Standard GKE, the command works as expected and the pods are running. As you mentioned, for Autopilot GKE, ``-n cert-manager`` needs to be specified and then the pods are running. Few observations:

I see the following warnings with autopilot:
```
Warning: Autopilot set default resource requests for Deployment cert-manager/cert-manager-cainjector, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/cert-manager-cainjector created
Warning: Autopilot set default resource requests for Deployment cert-manager/cert-manager, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/cert-manager created
Warning: Autopilot set default resource requests for Deployment cert-manager/cert-manager-webhook, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/cert-manager-webhook created
Warning: AdmissionWebhookController: mutated namespaceselector of the webhooks to enforce GKE Autopilot policies.
```
I see the following [here](https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml):
```
name: cert-manager-cainjector:leaderelection
  namespace: kube-system
```
Since this is the case, how do we override ``global.leaderElection.namespace`` from **kube-system** to **cert-manager**?  I see the Helm option "--set global.leaderElection.namespace=cert-manager". Can we do this with ``kubectl``?

**Review by dewan-ahmed — COMMENTED** [review]
Hi @kevinbowman-aiven thanks for this clarification. I validated that on Standard GKE, the command works as expected and the pods are running. As you mentioned, for Autopilot GKE, ``-n cert-manager`` needs to be specified and then the pods are running. Few observations:

I see the following warnings with autopilot:
```
Warning: Autopilot set default resource requests for Deployment cert-manager/cert-manager-cainjector, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/cert-manager-cainjector created
Warning: Autopilot set default resource requests for Deployment cert-manager/cert-manager, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/cert-manager created
Warning: Autopilot set default resource requests for Deployment cert-manager/cert-manager-webhook, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/cert-manager-webhook created
Warning: AdmissionWebhookController: mutated namespaceselector of the webhooks to enforce GKE Autopilot policies.
```
I see the following [here](https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml):
```
name: cert-manager-cainjector:leaderelection
  namespace: kube-system
```
Since this is the case, how do we override ``global.leaderElection.namespace`` from **kube-system** to **cert-manager**?  I see the Helm option "--set global.leaderElection.namespace=cert-manager". Can we do this with ``kubectl``?

**Comment by dewan-ahmed** [comment]
Makes sense. Do you think mentioning ** into ``cert-manager`` namespace** might be a bit more clear instead of **into a specified namespace**? This is just nits.

**Comment by kevinbowman-aiven** [comment]
Yeah absolutely, I'm happy with nit-picking :)  I'll update the PR (although I also don't mind if you want to make tweaks yourself, I'm not precious about it).

**Pull request merged**
