### PR TITLE
Add descriptions and grouping to the postgresql extensions list

### PR DESCRIPTION
**Pull request by lornajane**
# What changed, and why it matters

Request from a customer and support team, adding one-line descriptions for each extension. Layout is inspired by #558 which gives more space for words than the table layout did. I also tried to group similar extensions together but I think this part could use some work.

### CODE REVIEW

**Comment by ftisiot** [comment]
A question for clarification: in this version we're showing the complete link vs the Grafana one where we had link labels as "GitHub" or "Grafana Docs".
I would be in favour of adding a link label, also because we could possibly add more links (e.g. for DBLink one to PG docs and one to our example in devportal) WDYT?

**Comment by lornajane** [comment]
I think labelling links, especially when the label is going to be the same in every entry, is a bit like throwing information away, and from an accessibility point of view, you have no idea where you are going (I can't hover; a screenreader user would only get "Docs" as the prompt to choose). So unless it's a big problem, having the information here is my preference, although not to the extent that I would want to argue about it.

**Comment by TibsAtWork** [comment]
I hadn't thought of the accessibility argument for the links, but having them explicit does make it a lot more obvious where they're going, at the penalty of a "messier" appearance. So I'm happy to go with the explicit URLs.

Do we want to make this a "style guide" decision for such collection-of-plugins/things pages? (and specifically, does that mean #558 would need to do the same - that's a bit more complicated because there are often two urls...)

I do like the gathering into categories - I feel more comfortable with some sort of "contents" for such a long page. And I think the categories make sense, although with minor comments:

* Should `postgres_fdw` and `dblink` go together as "cross database" tools? Two items is on the edge...
* Would it be worth moving some of them to a `deprecated` or something category? I'm looking at `intagg` and`pg_prometheus`. (Again, it's only 2 items at the moment, but moving them out of the main categories may make a bit more sense for things that one probably shouldn't/can't use)
* Also, the entry for `pg_primetheus` says it is replaced by `promscale`, but we don't have an entry for that.

Anyway, once you're happy with the list I would gladly approve the merge.

**Comment by lornajane** [comment]
Promscale is technically open source but it doesn't work well at all without an additional proprietary-licensed extension, so we don't offer it. I also took the liberty of removing from the list a bunch of extensions that are only available up until PG 10 (nobody should be deploying that version or enabling un-upgradeable extensions today, and it will save us having to remember to update when this is end of life later in the year). So that was chkpass, pg_partman, plv8, plcoffee and plls.

I don't think we need rules about you must or must not use links in certain ways; messier is absolutely the right way to describe this and there will be times when we come down on the other side of the compromise fence. Consistency within a page is probably the key (and we can edit it again later if we have got it wrong!)

**Review by TibsAtWork — APPROVED** [review]
I think this works well.

**Pull request merged**
