### PR TITLE
feat: add language to html tag

### PR DESCRIPTION
**Pull request by turq84**
# Task: HTML lang attribute missing [developer.aiven.io]
## Description: Issue details
93 Pages where the <html lang=“”> language attribute is missing, e.g. https://developer.aiven.io/docs/platform/howto/console-fork-service.html.

Although Google might not be using the HTML lang attribute today, other search engines and browsers do.

## How to fix
Make sure your pages have language (or language and country) code declared in the HTML lang attribute.
Note that the language code must conform to ISO 639-1 format.

# Solution
By referring to the base template, I used the example there to add the language feature to the `config.py` file. See this [link](https://github.com/pradyunsg/furo/blob/db4dd7395d7f962a1fd02e90eb3e182ca316d518/docs/conf.py#L78).

After I added the language parameter to the config file, I didn't see any changes on my localhost. I have noticed that sometimes new changes aren't visible. Maybe it's just my computer.

Preview URL: https://deploy-preview-197--developer-aiven-io-preview.netlify.app/

### CODE REVIEW

**Comment by lornajane** [comment]
I think I might need to bump the theme version to get this, let me dig into it a bit

**Comment by lornajane** [comment]
I think this did it, it puts the language into the opening html tag itself - does that seem correct to you @turq84 ?

**Comment by turq84** [comment]
Yep! I see it! :)

**Review by lornajane — APPROVED** [review]
We had to update the theme to see it but this looks perfect now. Thanks!

**Pull request merged**
