### PR TITLE
adding cloud security general topic to platform

### PR DESCRIPTION
**Pull request by hab-anka**
# What changed, and why it matters

Adding the general cloud security topic from https://help.aiven.io/en/articles/977466-cloud-security-overview into Platform concepts.

### CODE REVIEW

**Comment by hab-anka** [comment]
Hi team @diawarr and @lornajane - I added a general topic to the platform section (on cloud security). The idea is to develop this section with very high level concepts in Aiven, starting with this one. I am proposing to distinguish the KEY concepts from ALL concepts in the container topic. Your feedback is welcome!

**Comment by lornajane** [comment]
I like the idea of a "curated collection" over just having the automatic collection index pages. But having both on the page means we're seeing the cloud security topic twice. I'm not sure if it is a huge problem, but I'm definitely noticing it.

**Comment by hab-anka** [comment]
I think in general we need to work more on how topics are included in navigation (both in the nav - which I think right now includes topics in alphabetical order, and in container topics). Ideally we would bring all topics in manually, in the order of their importance for the user flow. Which would prevent from having duplicates - just like this.

**Review by lornajane — APPROVED** [review]
Thanks!

**Pull request merged**
