### PR TITLE
Updated rate limit for connections/cpu/second per code

### PR DESCRIPTION
**Pull request by runwuf**
Updated rate limit for connections/cpu/second per code in aiven-core

### CODE REVIEW

**Comment by ftisiot** [comment]
Hi @runwuf, the change looks ok but I can't validate it since I don't know how to confirm it it's correct. Could you ask to review the correctness of the info from some of our core devs?

**Comment by ftisiot** [comment]
@runwuf, checking this, did you have the chance of asking one of the core devs?

**Comment by runwuf** [comment]
> @runwuf, checking this, did you have the chance of asking one of the core devs?

Hi @ftisiot
Thanks for your patience, this was driven out of this conversation.
https://aiven-io.slack.com/archives/C01TMVAHJ2W/p1673387354525469?thread_ts=1673248007.311269&cid=C01TMVAHJ2W
I will DM you direct link to the code.

**Review by harshini-rangaswamy — APPROVED** [review]
Looks good to me. Thanks

**Pull request merged**
