### PR TITLE
Add security policy

### PR DESCRIPTION
**Pull request by laysauchoa**
If someone finds some security vulnerability, how can they report? 
It would be nice to have short steps on a Security policy for this repository.

Fixes: https://github.com/aiven/devportal/issues/1123

### CODE REVIEW

**Comment by anelook** [comment]
This is nice I have a couple of notes: 
- from https://hackerone.com/aiven_ltd I see that it is for services, but it is not completely obvious from the text if it is for DevPortal or for Aiven services. 

- should this be  SECURITY.md  visible only to contributors of dev portal, or more noticeable article inside dev portal? 
Security audience interested in breaking Aiven services is most probably different from those who are making documentation contributions.

**Comment by laysauchoa** [comment]
> - from https://hackerone.com/aiven_ltd I see that it is for services, but it is not completely obvious from the text if it is for DevPortal or for Aiven services.

I believe we can make small adjusts in the text but I was recommended to use the general policy for Aiven.

> - should this be SECURITY.md visible only to contributors of dev portal, or more noticeable article inside dev portal?

In my opinion, this is the right place to add because it will link on GitHub to our "Security Policy", and this is the standard for OSS projects. 

> - Security audience interested in breaking Aiven services is most probably different from those who are making documentation contributions.

So the security policy allows a safe way to contact the maintainer to disclose vulnerability, so it is not disclosed in public as it could affect the people who use the code. We have a lot of examples here and if for some reason an example can be harmful somehow, then we should have a way to be contacted about it. So we can take the right actions after.

**Comment by anelook** [comment]
I see, thanks for explaining, now I understand better. Yes, in this case the location totally makes sense.
Should https://hackerone.com/aiven_ltd?type=team updated to clearly include developer portal resources?

**Comment by laysauchoa** [comment]
Hi @jlprat do you think we can include this there? or how this can be done? alternatively, if the devportal can not be included there, how should the reader proceed if some vulnerability is on the code? thanks in advanced

**Comment by jlprat** [comment]
I'd involve @st3fan because in the end this is a security policy.
@st3fan what do you think?

**Comment by lornajane** [comment]
@jlprat  @st3fan do you have concerns that should block this merge? I'd like to go ahead, even if we amend later

**Review by jlprat — APPROVED** [review]

**Pull request merged**
