### PR TITLE
Add rotating grafana creds article

### PR DESCRIPTION
**Pull request by FloorD**
Closes Migrate article: Rotating Grafana service credentials #829
@TibsAtWork was keen to look at the code block in the numbered list.

### CODE REVIEW

**Comment by laysauchoa** [comment]
Hi, thanks for the PR. There are some small issues with the build, just some small issues. If you are not able to run the checks locally or if I can help you somehow, let me know. 

About the image on this PR, do you think it adds more information? I'm not sure the image brings new information besides which is already explicit in the text. We would need to provide maintenance to this image to guarantee that it is updated. This is why I think is okay to ask ourselves if this bring more information or not.

**Comment by lornajane** [comment]
@TibsAtWork this is assigned to you, what's the next step?

**Comment by TibsAtWork** [comment]
It works as advertised. Just checking on the Sphinx/Vale failure before I approve.

**Review by TibsAtWork — APPROVED** [review]
Confirmed that it works as described.
Rewrote the text slightly, mainly to make the linter happy with the `avn` link, but also to remove a very long sentence.

**Pull request merged**
