### PR TITLE
Enhancements to PG Getting Started Page

### PR DESCRIPTION
**Pull request by ftisiot**
Initial Enhancement, this is just a draft, creating the PR for Anna Demo

### CODE REVIEW

**Comment by lornajane** [comment]
Can you take a look at the build failure?

**Comment by ftisiot** [comment]
looking at it now

**Review by lornajane — APPROVED** [review]
Nice! Especially the sample dataset. I think this should get people started pretty quickly.

**Comment by lornajane** [comment]
@hab-anka Can you take a look at this change too please? In particular, would you add something after step 6? The user has a database, with data in it ... should there be a call to action there to get them to play with it or do something else if they want to?

**Pull request merged**
