### PR TITLE
Migrate influxdb docs

### PR DESCRIPTION
**Pull request by FloorD**
Migrating the InfluxDB help docs, reference: #788  
Adds index page for InfluxDB and changes both toc and devportal's index page.

### CODE REVIEW

**Comment by FloorD** [comment]
Noticed the headers are not sentence case, so this definitely needs another review - hence the draft PR.

**Comment by lornajane** [comment]
@FloorD this won't get a review while the build is failing. Please let me know if you need a hand with anything here, I'll assign this to you - go ahead and unassign when it's ready for review and someone will pick it up!

**Comment by laysauchoa** [comment]
Currently, the build is failing. Let me know if we can support you somehow.

**Comment by lornajane** [comment]
Rebased to pick up newer changes to `main`.

**Comment by lornajane** [comment]
This pull request hasn't seen activity for some time, closing. Please re-open when you have time to work on this!

**Pull request closed without merging**
