### PR TITLE
Move to a nested structure for PostgreSQL HowTo content

### PR DESCRIPTION
**Pull request by lornajane**
# What changed, and why it matters

We have tooooooooo many items in the postgres/howto section of the navigation. This PR adds some structure to this and splits things up a bit - also adds some additional code samples (these are in their own commit and could be merged separately if that would be better).

### CODE REVIEW

**Review by hab-anka — CHANGES_REQUESTED** [review]
Nesting looks good. The new topics and TOC entries use Headline Style though... Not sure if the overwrite is working.

**Comment by lornajane** [comment]
Oops! We didn't review and merge the change that checks the headers so the functionality isn't available in other branches yet. It's #69, let's make this PR wait until that one is merged and I can make sure everything is as it should be.

**Comment by lornajane** [comment]
Thanks for catching this, rebased to include the additional check, and updated some titles/vocab. Could you take another look?

**Review by hab-anka — APPROVED** [review]
Looks good!

**Pull request merged**
