### PR TITLE
Migration article: Issue 808 - Attach VPC to AWS Transit Gateway 

### PR DESCRIPTION
**Pull request by dewan-ahmed**
# What changed, and why it matters

Resolves https://github.com/aiven/devportal/issues/808

This PR brings in an article on how to attach VPC to AWS TGW. [This](https://help.aiven.io/en/articles/3507710-attach-vpc-to-aws-transit-gateway) is the original help article that is being migrated to docs.aiven.io.

A reference to how to create VPC has not been added to this article yet since that article is still in review: https://github.com/aiven/devportal/pull/1310. Once #1310 is merged, I'll update this article to link the VPC creation step.

Note: In order to test this PR, you'll need AWS access.

### CODE REVIEW

**Comment by ftisiot** [comment]
@dewan-ahmed , I see some warnings in the build, mainly due to titles not in sentence case (or we need to add exception) could you please check?

**Comment by dewan-ahmed** [comment]
Fixed the Vale stuff @ftisiot 

My AWS account doesn't have sufficient privilege to create/modify AWS TGW so I requested that access. Meanwhile, someone else with such access could test that or we could trust the existing content and test later. Your call :)

**Comment by dewan-ahmed** [comment]
I have pinged the ticket owner today to remind about the request access.

**Comment by dewan-ahmed** [comment]
@etienne-aiven verified that the steps work

FYI  @TibsAtWork

**Review by TibsAtWork — APPROVED** [review]
Given the instructions have been verified, seems good to go.

**Pull request merged**
