### PR TITLE
Make addressable advanced config options

### PR DESCRIPTION
**Pull request by laysauchoa**
Fixes: https://github.com/aiven/devportal/issues/1400

### CODE REVIEW

**Review by ftisiot — COMMENTED** [review]
I'm not sure about the alignment, the "array" and description in the below image are not properly aligned, maybe we need to rethink about the structure?

misalignement of field type and desc

**Comment by laysauchoa** [comment]
Hi @ftisiot this was intentional because imho looks better. What would look better in your opinion? Here are some suggestions:

Screenshot 2022-09-22 at 11 31 14

Screenshot 2022-09-22 at 11 33 12

If you have a clear idea in your mind, would be possible to elaborate or show an example?

**Comment by ftisiot** [comment]
I would go for your second option
image

**Comment by laysauchoa** [comment]
it seems good to me @ftisiot I added now :)

**Review by ftisiot — APPROVED** [review]
LGTM!

**Pull request merged**
