### PR TITLE
Add "Connect with cqlsh" page to Cassandra documentation

### LINKED ISSUE #98: Cassandra connecting article
Detail how to find and use the connection details for this service

### PR DESCRIPTION
**Pull request by pparmin**
# What changed, and why it matters
I have added a connect article to our Cassandra documentation which shows how to connect by using `cqlsh`. 

## Possible improvements
I based this article roughly on the structure of the [Connect with redis-cli](https://developer.aiven.io/docs/products/redis/howto/connect-redis-cli.html) article. 

I think this article could be further improved by adding some information on how to verify the connection, similar to the `redis-cli` article. To my knowledge, Cassandra does not have a command like Redis' `INFO` command. If you have any suggestions here, please let me know :) 

Partly fixes #98

### CODE REVIEW

**Comment by pparmin** [comment]
Hey @ftisiot, thanks for looking into this! 
I looked at the warnings and the error, but it seems like the linter has generated them all for words that are part of the path and for the `certfile` parameter, which is how it is named. 

As far as I can tell, this should not create any issues. Let me know if I am wrong and I can change something about it.

**Comment by ftisiot** [comment]
Hi @pparmin, yeah in such cases (when we reference parameters with a fixed name) we usually mark them as code like ``certfile``, this will make the linter not checking it, the same goes for file paths ( i saw a `~/.cassandra/cqlshrc`).

**Comment by pparmin** [comment]
@ftisiot Thank you for the advice :) I made the necessary changes and marked all warnings/errors as code. The linter did not raise any further complaints.

**Comment by lornajane** [comment]
Clearing assignment and requesting review, I think this one got lost along the way but hopefully one or other Francesco can test this Cassandra connection and we can merge!

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
