### PR TITLE
Add Python autoformatter

### PR DESCRIPTION
**Pull request by laysauchoa**
Use psf/black to format Python code. Run once per week seems fine, but we can also change some of the customizations parameters from the workflow. This can be triggered manually and on the schedule.

Fixes: https://github.com/aiven/devportal/issues/1226

### CODE REVIEW

**Comment by laysauchoa** [comment]
Rebasing with main branch.

**Comment by jkowall** [comment]
No need to implement anything new on this IMO.

**Comment by laysauchoa** [comment]
Hi @jkowall, I am not so sure I understand your reasons to not have a formatter check for the Python code 🐍. You can check that the sample code on ``code/products/cassandra/connect.py`` does not work for the user, and having such formatter check would prevent that.

**Comment by jkowall** [comment]
We are moving away from this codebase in the coming months, so we'll not be using the code here. The current thoughts are migrating the docs to a standard [docusaurus](https://docusaurus.io/) based system. Much of the developer content will be moving to our new developer center once that is launched.

**Pull request closed without merging**
