### PR TITLE
Initial Redis draft - structure, intro, get started

### PR DESCRIPTION
**Pull request by hab-anka**
# What changed, and why it matters

Added initial structure:
- folders
- container topics

Initial drafts for:
- overview
- get started 
- get started concepts (high availability, high memory usage)
- migration
- ACL permissions

### CODE REVIEW

**Comment by lornajane** [comment]
Since this PR is still in progress (I think? The description implies there are still elements missing) I have marked it as draft so you can work on it and choose "Ready for review" when you are ready for a formal review from another team member.

**Comment by hab-anka** [comment]
Re-requesting review after having removed (hidden in comments) sections that were work in progress.

**Comment by hab-anka** [comment]
Hey @lornajane can you help out with this one? The build is failing and I am not sure what else to do.
Thanks in advance!

**Comment by lornajane** [comment]
I started looking at the build errors and ended up fixing a few things on one page, need to take another look next week at the rest (and some warnings because the reference section is empty, perhaps we should remove this until we need it). The main thing was that an image was missing an alt tag.

**Review by lornajane — APPROVED** [review]
This is in good shape, I just polished up a few things

**Pull request merged**
