### PR TITLE
add DR scenario explanation and process

### PR DESCRIPTION
**Pull request by encima**
# What changed, and why it matters
This could go under a new `support` folder but added to `concepts` here. Add Disaster Recovery explanation, how to request it and briefly how it works (maybe more technical details should be added?)

### CODE REVIEW

**Comment by encima** [comment]
The Aiven for PostgreSQL linting but I assume we should not add the ® as it implies the Aiven naming is trademarked with PG.
The `aiven` recommendation is within an email but unsure how to ignore this one 🤦‍♀️

**Comment by TibsAtWork** [comment]
I do like this article, and it seems a reasonable place to put it to me.

I've made a couple of fixes:

* It isn't necessary to add `Disaster Recovery` to the dictionary, as both `disaster` and `recovery` are in the default dictionary (and the capitalisation is ignored). I'm not actually sure how a "word" with a space in it would be used, either.
* The underlining for a reStructuredText title always needs to be at least as long as the title text. I've fixed that for the top title.
* `Aiven for PosgreSQL®` is the correct form - the `®` is taken to belong to PostgreSQL, and the use of "for" is enough to indicate we're not claiming any ownership of the PostgreSQL name.
* The email address problem is down to a weirdness of how the linting is done, and the only workaround we've got (which I've used) is to specify `support@Aiven.io` as the email "text". This looks odd to me, but is a perfectly valid form of our email address (and will work).

In order for the document to appear in the right place in the navigation, it also needs adding to the `_toc.yml` file at the top-level of the source tree. If you want me to help with that, please do ask

**Comment by encima** [comment]
> I do like this article, and it seems a reasonable place to put it to me.
> 
> I've made some fixes:
> 
> * It isn't necessary to add `Disaster Recovery` to the dictionary, as both `disaster` and `recovery` are in the default dictionary (and the capitalisation is ignored). I'm not actually sure how a "word" with a space in it would be used, either.
> * The underlining for a reStructuredText title always needs to be at least as long as the title text. I've fixed that for the top title.
Thank you!
> * `Aiven for PosgreSQL®` is the correct form - the `®` is taken to belong to PostgreSQL, and the use of "for" is enough to indicate we're not claiming any ownership of the PostgreSQL name.

Hmm, that seems to me like Aiven holds the trademark but I have no idea whether that is true!

> * The email address problem is down to a weirdness of how the linting is done, and the only workaround we've got (which I've used) is to specify `support@Aiven.io` as the email "text". This looks odd to me, but is a perfectly valid form of our email address (and will work).

Couldn't an exception be added to the linter for `@aiven` instead of `aiven`? 

> In order for the document to appear in the right place in the navigation, it also needs adding to the `_toc.yml` file at the top-level of the source tree. If you want me to help with that, please do ask

Thanks! I have done that now. Cheers for the quick turnaround!

**Comment by TibsAtWork** [comment]
The "Aiven for XXX<mark>" approach is the official way to do it - contact me outside github if you want more (too much!) detail 😄 

The email address linting is a good point. I had thought it was a problem with no solution (given our toolchain), but a bit more investigation suggests it might be fixable with some work on our linting rules. Unfortunately that's not going to happen now, but it is now on my backlog to investigate further.

**Comment by TibsAtWork** [comment]
Apologies - nearly there, but I'd forgotten that `docs/platform/concepts.rst` is the one case (I think) where the summary page actually has content that is written by hand. You can see this at https://deploy-preview-854--developer-aiven-io-preview.netlify.app/docs/platform/concepts.html - the sidebar has your new page, but it's missing from the main page text.

Could I get you to add a summary at the end, similar to the others already there. and then I'll approve?

(I think the new page gives just the right amount of information, by the way - more technical details are always tempting, but then they may go out-of-date, and also are probably best explained in a proper dialogue with the customer once they've contacted support.)

**Comment by encima** [comment]
> Apologies - nearly there, but I'd forgotten that `docs/platform/concepts.rst` is the one case (I think) where the summary page actually has content that is written by hand. You can see this at https://deploy-preview-854--developer-aiven-io-preview.netlify.app/docs/platform/concepts.html - the sidebar has your new page, but it's missing from the main page text.
> 
> Could I get you to add a summary at the end, similar to the others already there. and then I'll approve?
> 
> (I think the new page gives just the right amount of information, by the way - more technical details are always tempting, but then they may go out-of-date, and also are probably best explained in a proper dialogue with the customer once they've contacted support.)

Thanks for the feedback! That is a good point about leaving out specifics. If more are requested then we can always add later.

Added now and hopefully it makes sense/passes Vale!

**Comment by TibsAtWork** [comment]
It passes `make html` (apart from one known issue, not yours) and `make spell` on my machine, as well as passing CI.

**Pull request merged**
