### PR TITLE
Updating provider and service versions.

### PR DESCRIPTION
**Pull request by dewan-ahmed**
# What changed, and why it matters

This PR updates Aiven Terraform Provider and Aiven product versions. The new versioning practice for the provider is `~> X.Y.Z` rather than `>= X.Y.Z` which allows the patch version to be greater than Z but requires the major and minor versions (X.Y) to match the version that the configuration specifies. 

The product versions are updated to their latest available versions.

### CODE REVIEW

**Comment by dewan-ahmed** [comment]
Once I test running all the code for each recipe, I'll mark this PR ready for review.

**Comment by dewan-ahmed** [comment]
I have testes all 13 recipes to ensure they reflect up-to-date provider and product versions. Please test and review. Thanks.

**Review by anelook — CHANGES_REQUESTED** [review]
Thank you for updating terraform scripts! Almost had no issues testing them, the only problem I noticed is that the script for Kafka + OpenSearch didn't create the connection. Services and Kafka connect were created, but there is no sink connect from kafka to OpenSearch. (I left the services in dev-advocates, so you can see them running)

Also, /docs/tools/terraform/get-started.html contains version 3.1

terraform {
  required_providers {
    aiven = {
      source  = "aiven/aiven"
      version = ">= 3.1"
    }
  }
}

Is it supposed to be like this?

Lastly, I had issues testing Debezium, because I didn't have VPC and similar with MongoDB, which provider did you use to test MongoDB?

**Comment by dewan-ahmed** [comment]
Hi @anelook thanks for testing this PR - I know it must've taken you a lot of time! 

For the opensearch sink connection to Kafka, is this what you're looking for?

Screenshot 2022-12-01 at 2 01 11 PM

Good catch with the get-started version. I added it via https://github.com/aiven/devportal/pull/1606/commits/71191313ccd83679ca1c0a880e978546ccfc5a9d

To test MongoDB, you can create a mongodb instance on any managed provider like AWS or Google Cloud or even on MongoDB hosted. Then you can add the mongodb URI in the variable. 

@fmanimali authored the Debezium recipe which has the VPC part. I don't have that setup. @fmanimali could you please test the Debezium recipe to make sure the setup still works? Thank you.

**Comment by dewan-ahmed** [comment]
Sorry for pushing changes after you tested @anelook but we now have a newer version of the Terraform provider and there was a fix for ClickHouse which went in. My recommendation would be to merge this PR based on the previous testing while we discuss:
1. How to automate the testing of the recipes
2. How to test the recipes that have external environment dependencies like a MongoDB URI or creation of a VPC.

**Comment by dewan-ahmed** [comment]
Tagging a few colleagues as I believe this PR can be merged now while we discuss testing recipes with external dependencies at a later time: @mhoffm-aiven @byashimov @lornajane

**Comment by anelook** [comment]
I agree with @dewan-ahmed, we need an automated way to test this. A project with complete setup that is either automated to run periodically or we run it manually on some regular basis.

**Comment by dewan-ahmed** [comment]
Thanks to @byashimov, we have https://github.com/aiven/devportal-terraform-examples where we'll be adding recipes for automated testing. 

For now, @anelook would you be able to merge this PR please as the changes of the PR updates only the provider and product versions?

Thanks again for reviewing this 🙏🏽

**Review by anelook — APPROVED** [review]
Looks good to me. As a next step we need an automated or semi-automated way to test the changes.

**Pull request merged**
