### PR TITLE
platform: add new cloud region - google-europe-west12-turin-italy

### PR DESCRIPTION
**Pull request by wojcik-dorota**
https://aiven.atlassian.net/browse/DOC-638

### CODE REVIEW

**Review by rominf — APPROVED** [review]

**Review by rominf — DISMISSED** [review]
Here is the screenshot of a preview:

image

I think the ordering of geographical names is wrong, hierarchical ordering looks more usual:
```
Europe, Italy, Milan
Europe, Italy, Turin
```

Also, it's easy to forget to update existing regions in case of new region appearance with the same name (like here). I suggest to **always** (meaning for all existing and new regions!) follow the same naming pattern as in Console, other clients, and API, except for removing cloud provider name in the middle of the string. So in Aiven Console the region is named as: 
```
Europe, Italy - Google Cloud: Turin
```
here I would replace `- Google Cloud: ` with `, ` and make it:
```
Europe, Italy, Turin
```

What do you think?

**Comment by wojcik-dorota** [comment]
> Here is the screenshot of a preview:
> 
> image
> 
> I think the ordering of geographical names is wrong, hierarchical ordering looks more usual:
> 
> ```
> Europe, Italy, Milan
> Europe, Italy, Turin
> ```
> 
> Also, it's easy to forget to update existing regions in case of new region appearance with the same name (like here). I suggest to **always** (meaning for all existing and new regions!) follow the same naming pattern as in Console, other clients, and API, except for removing cloud provider name in the middle of the string. So in Aiven Console the region is named as:
> 
> ```
> Europe, Italy - Google Cloud: Turin
> ```
> 
> here I would replace `- Google Cloud: ` with `, ` and make it:
> 
> ```
> Europe, Italy, Turin
> ```
> 
> What do you think?

Totally agree 👍🏻 I'll fix the names for the two regions on this PR. For the rest of the fixes, I'll create a DOC Jira ticket to follow up.

**Review by rominf — APPROVED** [review]

**Review by rominf — DISMISSED** [review]
Ah, sorry for premature approval. I believe your commits should be squashed into one, because it's really a single change.

**Comment by wojcik-dorota** [comment]
> Ah, sorry for premature approval. I believe your commits should be squashed into one, because it's really a single change.

Thanks, @rominf :-) FYI, in the devportal repo, we don't follow strictly the squashing policy and just keep the commits as we find them useful.

**Comment by rominf** [comment]
@wojcik-dorota The region is available on aiven.io - the PR can be undrafted.

**Comment by wojcik-dorota** [comment]
> @wojcik-dorota The region is available on aiven.io - the PR can be undrafted.

@rominf , thanks for letting me know. Please approve so that I can merge.

**Review by rominf — APPROVED** [review]

**Pull request merged**
