### PR TITLE
Aiven cli service flink

### PR DESCRIPTION
**Pull request by ftisiot**
# What changed, and why it matters
Added the Flink commands

### CODE REVIEW

**Comment by lornajane** [comment]
Well, this branch adds the line, so if we merge this now, it will add it, which we don't want. So yes, I think the error (meaning the case-insensitive opensearch spelling) was introduced in both branches and should be fixed in both branches.

**Review by anelook — APPROVED** [review]
Run all the commands, found only one issue that cancelling a failed (or already cancelled) job will return a long confusing error. But Flink team is already aware of it and they have a Jira ticket. Therefore - approving this pull request. It is very helpful stuff for the CLI users

**Comment by lornajane** [comment]
is someone rebasing for conflicts and then merging this @anelook or @ftisiot ? Do you need me to do something?

**Comment by lornajane** [comment]
@ftisiot could you please comment on the status of this pull request? It's approved, but has conflicts.

**Comment by ftisiot** [comment]
Weirdly enough I didn't see any notifications about this. I'll probably need to add additional work on it since we're going to add a couple more parameters to table and job creation this or the next week.

**Pull request merged**
