### PR TITLE
Kafka connect headings and nav entry updates

### PR DESCRIPTION
**Pull request by lornajane**
# What changed, and why it matters

This request came from Developer Marketing to improve the consistency and discoverability of our excellent connector documentation

### CODE REVIEW

**Comment by lornajane** [comment]
@argkastan could you also take a look? You don't seem to be a member of the github org so I can't add you as a reviewer.

**Comment by argkastan** [comment]
Does somebody need to invite me for that?

**Review by petralylander — APPROVED** [review]
💪 All good!

**Comment by ftisiot** [comment]
@petralylander @argkastan if you're both happy I can merge the change, could you please confirm?

**Comment by argkastan** [comment]
> @petralylander @argkastan if you're both happy I can merge the change, could you please confirm?

Everything seems ok @ftisiot !
Thank you for the changes

**Comment by ftisiot** [comment]
Thanks @lornajane for the changes!

**Review by ftisiot — APPROVED** [review]
LGTM

**Comment by petralylander** [comment]
Confirmed, approved and ready to go, yes!

**Pull request merged**
