### PR TITLE
initial import of GCP marketplace article with edits to update it to V2

### PR DESCRIPTION
**Pull request by encima**
# What changed, and why it matters

Migration of GCP marketplace article #1140 with updates to v2 support. Mostly calling out the need to sign up using the email. Possibly could use more explanation of the Aiven GCP console with a screenshot?

### CODE REVIEW

**Comment by lornajane** [comment]
Formatting note: we have a few different ways shown here for things that I think are labels in the interface. The full guidelines are here https://github.com/aiven/devportal/blob/main/CONTRIBUTING.rst#formatting-guidelines but bold for UI things, and code/literal for code things, would be better.

**Comment by kevinbowman-aiven** [comment]
Factually looks good to me, I haven't run the steps though as our cloud accounts are still getting marketplace permissions setup.

Only glitch I saw was that the TOC doesn't seem to be getting updated (https://deploy-preview-1143--developer-aiven-io-preview.netlify.app/docs/platform/howto/list-billing.html)

**Comment by lornajane** [comment]
I've fixed the missing navigation entry, but we'll need someone with the right GCP access to run through the steps, and I'm not sure who that would be.

**Comment by encima** [comment]
I have run through the steps with an external GSuite account

( https://www.facebook.com/aivencloud ) ( https://twitter.com/aiven_io ) ( https://www.linkedin.com/in/christopher-gwilliams-51322924/ )

Dr. Chris Gwilliams

Staff Solution Architect

Solution Architecture | Aiven

+358444915385

***@***.***

aiven.io ( http://aiven.io )

Helsinki, Finland

**Review by lornajane — APPROVED** [review]
On the basis that @encima knows what he's doing, and it sounds plausible, and that I would rather have this probably-correct and public rather than hanging around in a pull request queue for weeks - I'm approving. Thanks Chris :)

**Pull request merged**
