### PR TITLE
Migration of https://github.com/aiven/devportal/pull/new/aws-privatelink-step-by-step

### PR DESCRIPTION
**Pull request by fmanimali**
This is the article being migrated from help.aiven.io:
"5858370-aws-privatelink-setup-step-by-step-using-aiven-and-aws-web-console"

# What changed, and why it matters

### CODE REVIEW

**Review by fmanimali — COMMENTED** [review]
Lint doesn't realise that the word "aiven" is in a URL.
@ftisiot can you kindly review and approve?

**Comment by ftisiot** [comment]
Hi @fmanimali the PR still contains errors and warnings. 
The error in the image is due to a missing `:alt:` tag

**Comment by ftisiot** [comment]
I would discuss this article: we currently have https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks.html for the usage of AWS Privatelinks with Aiven, what has this article on top of it? Maybe for @dewan-ahmed ? Once we confirm the need I can work on fixing the shape of it if needed

**Comment by dewan-ahmed** [comment]
@fmanimali from my understanding, https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks.html serves the purpose of the CLI version of "How to use AWS privatelink with Aiven" and this PR brings in the web (Aiven console) version. 

Since we focus mostly on the Aiven console for `docs/platform/howto`, my suggestion is to update https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks.html to include the unique contents from https://help.aiven.io/en/articles/5858370-aws-privatelink-setup-step-by-step-using-aiven-and-aws-web-console rather than creating a separate article.

Suggested format:

1. Include the diagram from https://help.aiven.io/en/articles/5858370-aws-privatelink-setup-step-by-step-using-aiven-and-aws-web-console
2. Include the steps to create the privatelink using Aiven console from https://help.aiven.io/en/articles/5858370-aws-privatelink-setup-step-by-step-using-aiven-and-aws-web-console
3. Under a separate section of the same page, add the contents from https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks.html as the steps to do the same using Aiven CLI

**Comment by dewan-ahmed** [comment]
@fmanimali pinging to request your 👀 on this PR. Let's try to move this forward 🙏🏽

**Comment by dewan-ahmed** [comment]
@ftisiot @fmanimali I propose we close this PR due to inactivity. What's your thoughts?

**Comment by lornajane** [comment]
This was identified as a high priority migration article, we do need this content and the pull request should not be closed. If @fmanimali isn't available to lend his expertise, please find someone else who can help, or work through the steps yourself and see if you can get the issue to a publishable state.

**Comment by lornajane** [comment]
(also the branch is very stale, please let me know if you'd like me to rebase to give this a new lease of life)

**Comment by dewan-ahmed** [comment]
Hi @lornajane, yes please, rebasing would be great.

The main reason I couldn't tech review is because I don't have sufficient permission on the internal shared AWS account. For another PR, someone from the security team validated the steps when I opened a ticket to request more access. I have created one more ticket requesting access to be able to create/modify AWS VPC, TGW resources. Since there is only one shared project, I believe that there's strict control on allowing access.

**Comment by dewan-ahmed** [comment]
Update: as of today, DevRel doesn't have required access to test this PR. A Halp ticket remains open and the team is aware of our need.

**Comment by lornajane** [comment]
Rebased to bring the article into the current version of the docs platform. This was identified as a key article, but I now have questions about how it compares to https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks which looks similar.

**Comment by dewan-ahmed** [comment]
@fmanimali what's your take on
> how it compares to https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks which looks similar

**Comment by celestehorgan** [comment]
@TibsAtWork to take a look at this and see if it's combine-able with the page mentioned.

**Comment by angelinekwan** [comment]
@TibsAtWork Build error
error

**Comment by wojcik-dorota** [comment]
I propose to close this PR: we already have https://docs.aiven.io/docs/platform/howto/use-aws-privatelinks available in the Aiven public docs.

**Comment by staceysalamon-aiven** [comment]
Closing this as we have an AWS Private Link article and can add other information on a fresh branch later as needed.

**Pull request closed without merging**
