### PR TITLE
New article for using dsbulk with cassandra

### LINKED ISSUE #1355: Write an article for customers to use DSBULK to load/unload and count in AIven service for cassandra.
# What should we add to our content collections?

a step-by-step procedure to download, install and use dsbulk to load, unload and count data in cassandra

# Is this something you would work on yourself?

YES, I will write up the article and submit a PR for it.
[X] I plan to open a pull request for this

### PR DESCRIPTION
**Pull request by fmanimali**
# What changed, and why it matters

This is a new HOW-TO article to use dsbulk to do the needful with cassandra

Fixes #1355

### CODE REVIEW

**Comment by fmanimali** [comment]
let me know if I need to do anything here.

**Comment by lornajane** [comment]
It's always fine to ping! All PRs are open for any Aivener to review - it's conference season so DevRel bandwidth is very limited in September and October, response times are slower than at other times of year.

**Comment by lornajane** [comment]
There were so many minor problems here that I ended up pushing a commit rather than writing a long explanation of what to fix in an attempt to get that out of your way @fmanimali . I've added the project name DSBulk as a recognised word, but the command `dsbulk` always needs to be marked up as code/literal, which in restructured text is two backticks, rather than one as markdown is. Hope this helps.

**Comment by lornajane** [comment]
@TibsAtWork could you take a look at what is upsetting Vale here? I'm not sure how to fix (or why we have two linkcheck tasks of which one runs vale ....)

**Comment by fmanimali** [comment]
@ftisiot I have checked and content is tsill good and correct. Please merge

**Review by ftisiot — APPROVED** [review]
LGTM

**Pull request merged**
