### PR TITLE
Help article: SAML Okta how-to

### LINKED ISSUE #812: Migrate article: Setting up SAML authentication with Okta
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3438800

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

### PR DESCRIPTION
**Pull request by runwuf**
Migrated Setting up SAML authentication with Okta help article.

Fix #812

### CODE REVIEW

**Review by ftisiot — CHANGES_REQUESTED** [review]
Hi @runwuf, before I start a proper review, could you please assess which images are needed and which can be removed? Trying to minimise images is something that we are aiming since there's always an overhead in having them updated for every UI change

**Comment by runwuf** [comment]
@ftisiot got it, will remove some screenshots tomorrow, only keep the ones that's really needed.

**Comment by runwuf** [comment]
@ftisiot removed most of the screenshot, only kept one left.  This is now ready for review.

**Comment by ftisiot** [comment]
thanks @runwuf ! Could I please also ask to re-use the structure of similar SAML articles like https://docs.aiven.io/docs/platform/howto/saml/setup-saml-onelogin.html

Specifically around:
* Section titles
* Parameters table 
Thanks!

**Comment by runwuf** [comment]
> thanks @runwuf ! Could I please also ask to re-use the structure of similar SAML articles like https://docs.aiven.io/docs/platform/howto/saml/setup-saml-onelogin.html
> 
> Specifically around:
> 
> * Section titles
> * Parameters table
>   Thanks!

done, hope this looks good.

**Comment by ftisiot** [comment]
Hi @runwuf , I made some edits to the document, could you please check the correctness of all the points? 

One q: the `Assign users to the Okta application` should that section be near the `Setup on Okta` one? since it's referring to a step that needs to be done on the Okta side?

**Comment by mparikhaiven** [comment]
@ftisiot , @runwuf - Actually screenshots in the original PR were immensely useful for someone who is configuring this set up the first time, may it be a customer on-boarding with Aiven or an CS person doing this first time around. 

In large scale enterprise customer situation, more the screenshot and detailed, better it is TBH.

At a minimum, I feel we should preserve these screenshots in addition to the ones that we see in latest commit.
images/platform/howto/saml/okta/okta-edit-method.png
images/platform/howto/saml/okta/okta-saml-configuration-urls.png
images/platform/howto/saml/okta/okta-saml-settings.png

**Comment by runwuf** [comment]
> @ftisiot , @runwuf - Actually screenshots in the original PR were immensely useful for someone who is configuring this set up the first time, may it be a customer on-boarding with Aiven or an CS person doing this first time around.
> 
> In large scale enterprise customer situation, more the screenshot and detailed, better it is TBH.
@ftisiot @mparikhaiven 

IMHO some of these how-to guide could be quite challenging to follow when there are multiple consoles/portals/sites involved, examples are such as SAML integration and VPC between different clouds and etc.

To keep up screenshots up-to-date with UI updates in a document is quite a bit of effort.  Here's an idea - how about keep to minimal to no screenshots in these tutorials, but embed with a short video demo the whole process?

**Comment by ftisiot** [comment]
I believe the video will have similar problems to a guide... since UI change quite rapidly... 
I would suggest, if the 3 screenshots are needed, to include them, it's something we'll have to maintain, but at the same time, it's not 10 screenshots.

**Comment by ftisiot** [comment]
@runwuf can you take care of re-including the screenshots? Sorry for the double work

**Comment by runwuf** [comment]
Will do, didn't have a chance today but will try tomorrow.

**Review by ftisiot — APPROVED** [review]
LGTM thanks @runwuf

**Pull request merged**
