### PR TITLE
IOPS PostgreSQL correction

### PR DESCRIPTION
**Pull request by laysauchoa**
correction of IOPS values
Related to https://github.com/aiven/devportal/pull/573

### CODE REVIEW

**Comment by Aiqin-Aiven** [comment]
lgtm, we have different vm types for those plans, but when put pg and mysql together, I think it makes sense to have identical ones. Thanks for helping update those.

**Comment by laysauchoa** [comment]
@ftisiot can you check and approve it? I can not approve myself

**Review by ftisiot — COMMENTED** [review]
LGTM

**Comment by ftisiot** [comment]
Not sure why, but looks like we need @Aiqin-Aiven to approve before mergin

**Comment by laysauchoa** [comment]
@Aiqin-Aiven pls approve it and we can merge it

**Review by Aiqin-Aiven — APPROVED** [review]
LGTM

**Pull request merged**
