### PR TITLE
Add forum, meetups to community page

### PR DESCRIPTION
**Pull request by FloorD**
Adding a reference to the forum and our meetups to the forum. 
TODO: add icons fro Discourse and Meetup, respectively. Please advise me what icon library should be used 🙏

### CODE REVIEW

**Comment by harshini-rangaswamy** [comment]
> Please advise me what icon library should be used 

Currently, most of the icons on the Community page are located in the **/images/social_media** directory. I'm wondering if it would make sense to consolidate all the icons into a single location like **/images/community**. Alternatively, if it works better, you can add the specific icons for Discourse and Meetup to the **/images/community** directory.

**Comment by FloorD** [comment]
I found the location, but I'd like to know where the others came from, so we can stay in the same style.

**Comment by harshini-rangaswamy** [comment]
> I found the location, but I'd like to know where the others came from, so we can stay in the same style.

Got it! I'm not entirely sure where the old icons were sourced from, but for Discourse and Meetup, Angeline has suggested using the following icons: 

- https://www.iconfinder.com/icons/939820/meetup_icon
- https://www.iconfinder.com/icons/4691569/discourse_icon

**Comment by staceysalamon-aiven** [comment]
@harshini-rangaswamy @FloorD Since we are migrating to a new platform soon, shall we close this? We can be sure to link to the community from the new site. :)

**Comment by harshini-rangaswamy** [comment]
> @harshini-rangaswamy @FloorD Since we are migrating to a new platform soon, shall we close this? We can be sure to link to the community from the new site. :)

Make sense!

**Pull request closed without merging**
