### PR TITLE
Add reference documentation for avn project command

### LINKED ISSUE #133: CLI docs for `avn project` command
Document the commands with this subcommand, including examples and an explanation of what it does

### PR DESCRIPTION
**Pull request by lornajane**
# What changed, and why it matters

Fixes #133 by adding documentation for the `avn project` subcommand, including explanations and examples. This is the first of the CLI reference docs to be added so general feedback is also welcome.

### CODE REVIEW

**Review by hab-anka — COMMENTED** [review]
I think this topic should be nested under the CLI entry, so that it is visible via the nav too.
The sub-commands entries could use a better formatting so that they stand out from the whole article. Right now they are grey and there is no spacing before them, so this looks like a long article with no headings.

**Comment by ftisiot** [comment]
I agree about having it available nested under the CLI entry. It will make easier to browse the commands in the future too!

**Review by ftisiot — APPROVED** [review]
All edits look in line with @hab-anka comments, Looks fine from me, leaving @hab-anka last review

**Review by hab-anka — APPROVED** [review]
Left a few changes in a commit, minor improvements (change of description to 3rd person, added punctuation and fixed some capitalizations).

**Pull request merged**
