### PR TITLE
Zookeeper access

### LINKED ISSUE #404: Migrate Zookeeper access
# What should we add to our content collections?

https://help.aiven.io/en/articles/5223663-zookeeper-access

# Is this something you would work on yourself?

[x] I plan to open a pull request for this

### PR DESCRIPTION
**Pull request by anelook**
Fixes #404

### CODE REVIEW

**Comment by lornajane** [comment]
Do we need to add some version caveats for this? I _think_ Kafka is without ZooKeeper, or can be without it, in newest versions (v3.0 or later)

**Comment by anelook** [comment]
Clarified with Kafka team

- We do run both Kafka 2.7 and 2.8 which do not have zookeeper-less mode, 2.8 being most common
- Our Kafka 3.0 still uses zookeeper as 3.0 was first version with I'd say experimental zookeeper-less mode
- In any case our customers can be relaxed, migration to zookeeper-less mode won't be visible to aiven customers

**Comment by laysauchoa** [comment]
this sgtm and only needs to solve the conflict.

**Review by laysauchoa — CHANGES_REQUESTED** [review]
only conflict file should be resolved here

**Review by laysauchoa — APPROVED** [review]
LGTM!

**Review by laysauchoa — APPROVED** [review]

**Pull request merged**
