### PR TITLE
Make our Vale rules error rather than warn

### LINKED ISSUE #1481: Turn misspelling warning into errors
Most of the spelling and title case errors being flagged as warning and therefore it does not making the build fail. We should turn the warning into errors, so it makes easier to review and to maintain the docs with correct words.

Reported by @ftisiot 

This should be done in some phases (following this order to work well):

- [ ]  Run the checks in all the documents and fix all warnings.
- [ ] Rebase open pull requests with the latest changes, so they do not break it.
- [ ] Merge the changes that will change the warning into errors for this cases.

### PR DESCRIPTION
**Pull request by lornajane**
# What changed, and why it matters

We have a policy of fixing all warnings - but they are easy to miss in the PR since they don't actually cause the build to fail. This bumps the severity of the rules so that these warnings must be fixed before merge.

Fixes #1481

### CODE REVIEW

**Comment by laysauchoa** [comment]
Hi, does this PR is related to this? https://github.com/aiven/devportal/issues/1481 If yes, does it make sense to link to the Issue?

**Comment by lornajane** [comment]
Good shout! Thanks @laysauchoa , added the issue to the description :)

**Comment by lornajane** [comment]
@TibsAtWork I tagged you for review on this one, I think you'd be the best person to check I haven't missed anything and merge it. We should probably rebase as we've let it get a bit stale for such a big step.

**Comment by TibsAtWork** [comment]
That sounds sensible.
I have a concern over `:ref:` and `:doc:` roles and the reproducibility of `make spell` on my local machine, which was my only concern. I may have more understanding of that now, so can try to test this tomorrow.

**Comment by TibsAtWork** [comment]
@lornajane can you confirm that if you do `make spell` locally, you don't get any errors due to `:doc:` or `:ref:`?

More specifically, if you do
```
vale --output=line docs/community/challenge/the-rolling-challenge.rst
```
you get no report?

Because I get
```
docs/community/challenge/the-rolling-challenge.rst:24:60:Aiven.common_replacements:Use 'Kafka' instead of 'kafka'.
docs/community/challenge/the-rolling-challenge.rst:24:134:Aiven.common_replacements:Use 'Flink' instead of 'flink'.
docs/community/challenge/the-rolling-challenge.rst:26:111:Aiven.common_replacements:Use 'Flink' instead of 'flink'.
docs/community/challenge/the-rolling-challenge.rst:99:117:Aiven.common_replacements:Use 'Kafka' instead of 'kafka'.
```
which I strongly believe to be due to some problem in my local setup (as that shouldn't happen).

If you're not getting the same problem, then I'll be happy to approve this PR, and I'll also know I definitely have a weird problem on my machine 😢

**Comment by lornajane** [comment]
I can confirm, I get no output from that page - and the GitHub CI doesn't seem to either.

Since this has gone a bit stale, I'll take the time to rebase.

**Comment by lornajane** [comment]
Tagging in a few more people, since we keep talking about this, and having to fix things, it would be good to move forward.

**Review by dewan-ahmed — APPROVED** [review]
With the branch already rebased and 👀 from other colleagues, I'll go ahead and merge this.

**Pull request merged**
