### PR TITLE
Order plugin list Grafana

### PR DESCRIPTION
**Pull request by FloorD**
Add more context to https://developer.aiven.io/docs/products/grafana/reference/plugins.html with external links and plugin descriptions. 

screencapture-localhost-8000-docs-products-grafana-reference-plugins-html-2022-02-09-20_35_21

I need to figure a few things out before I can submit the PR. 👇 

Plugins I could not find in the plugin marketplace on grafana.com: 
- Bar chart
- Bar gauge
- Gauge
- Geomap
- Getting Started
- Google Cloud Monitoring
- Jaeger
- Logs
- Loki
- Microsoft SQL Server
- News
- Node Graph
- Stat
- State timeline
- Status history
- Tempo
- TestData DB
- Time series
- Welcome
- Zipkin

_Google BigQuery_, which version?
https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/
https://grafana.com/grafana/plugins/grafana-bigquery-datasource/

_Plotly_, which version?
https://grafana.com/grafana/plugins/natel-plotly-panel/
https://grafana.com/grafana/plugins/ae3e-plotly-panel/

_Getting Started_... seems to be a mistake? Maybe _Welcome_ too?

SimpleJson, is no longer maintained by Grafana. Alternatives are [JSON](https://grafana.com/grafana/plugins/simpod-json-datasource/) or [JSON API](https://grafana.com/grafana/plugins/marcusolsson-json-datasource/).

### CODE REVIEW

**Comment by lornajane** [comment]
This PR has a broken link. This can be easiest to spot running the link checker locally but from the logs:

```
(docs/products/grafana/reference/plugins: line   98) broken    http://docs.grafana.org/reference/table_panel/ - 403 Client Error: Forbidden for url: https://grafana.com/docs/grafana/latest/reference/table_panel/
```

**Comment by lornajane** [comment]
Sorry, just another thing (I'm eyeballing this because I'm updating the postgres extensions page and very inspired by this example), we should have anonymous references for the links, so add another `_` after the link. I will also try to update the README with this tip because I think @ftisiot and I had to look this up recently too.

**Comment by FloorD** [comment]
@lornajane I've updated the link and references 🙏

**Comment by TibsAtWork** [comment]
Some general comments:
* In the Conversation for the PR, you say you need to work some things out, and give a list - is that done now?
* Same place, you ask "Google BigQuery, which version?" - is that resolved?
* Similarly, you ask "Plotly, which version?", but I can't actually see an entry for Plotly - ah, presumably it's Panel?
* Again, "JSON or JSON API" was presumably resolved in favour of Simple JSON?

Some of the descriptive texts re-use the name of the plugin ("The Discrete panel shows discrete values in a horizontal graph, plotting state transitions.") and some of them do not ("Displays time series data or geohash data from Elasticsearch overlaid on a world map."). In some cases I assume that's because the original description is from the appropriate web page, but it's not always so. I tend to feel that repeating the name isn't normally needed.
Feel free to argue with me about how much this is worth bothering with 🙂 

**But** I think this is a very good resource, and pretty much there. (it might be worth removing "WIP" from the title)

**Comment by FloorD** [comment]
@TibsAtWork All issues from the initial message have been resolved. I will do another round to remove some duplication!

**Comment by FloorD** [comment]
@TibsAtWork ready!

**Comment by TibsAtWork** [comment]
Looks very good to me. I've added some ® marks (hopefully correctly), attributed Elasticsearch, and changed "format the text" to "format it" to remove a slight repetition.

**Review by TibsAtWork — APPROVED** [review]
This is very nice, and I think the mini-descriptions are very useful.

**Pull request merged**
