### PR TITLE
Pride logo update

### PR DESCRIPTION
**Pull request by ftisiot**
# What changed, and why it matters

New pride logo for devportal!

### CODE REVIEW

**Comment by ftisiot** [comment]
Yep will do that, waiting for @FloorD to check with the team and act on merge

**Review by FloorD — APPROVED** [review]
Built locally and LGTM!

**Comment by laysauchoa** [comment]
**Timeline**
Just coming back about the timeline for where the image would be support, I've found this here: https://aiven.io/blog/celebrating-our-colorful-cast so we should just point out that timeline is 11 months from now and in case, it should change someone can take care of it.

**Tab image:**
Screenshot 2022-06-08 at 11 27 17

Is there a reason why the tab image was not replaced as well? I think it would be nice to actually support full mode in this case. What do you think?

**Tests:**
I've tested this with both mode: dark and light.

Screenshot 2022-06-08 at 11 12 36
Screenshot 2022-06-08 at 11 25 25

**Comment by laysauchoa** [comment]
Should we delete this branch for now?

**Pull request merged**
