### PR TITLE
mysql: add php example

### PR DESCRIPTION
**Pull request by sluhur**
code/products/mysql/connect.php
	docs/products/mysql/howto/connect-with-php.rst

# What changed, and why it matters

### CODE REVIEW

**Comment by lornajane** [comment]
Could you add some context about why this change is needed? Does it fix a bug, add a feature, or something else?

**Comment by laysauchoa** [comment]
I could not find a php example for mysql, could it be that you forgot to commit the file?

**Comment by sluhur** [comment]
> Could you add some context about why this change is needed? Does it fix a bug, add a feature, or something else?

This is an example on how to connect to MySQL using php. We have example on how to connect to PostgreSQL but not MySQL.

**Comment by sluhur** [comment]
> 
I have re-commit the files again.

**Comment by laysauchoa** [comment]
Hi, this seems good @sluhur! Thanks for adding this example. @lornajane would be possible to help us to review? I'm not familiar with php code.

**Review by lornajane — CHANGES_REQUESTED** [review]
This code sample doesn't work for me, and looks like a straight copy of the postgresql one which I'm not sure I'd quite expect since the SSL handling is probably different - did you test the code when creating this? Could you take another look please?

**Review by lornajane — APPROVED** [review]

**Comment by lornajane** [comment]
Thanks! I made some minor changes to make it a bit more "PHP" but this is a nice addition.

**Pull request merged**
