### PR TITLE
A fix and more reliability for the vale tests

### PR DESCRIPTION
**Pull request by TibsAtWork**
Vale has changed behaviour slightly (see comments in the `shelltest.text` file for the "bad references" test), so take account of that.

Also revert to piping the tests through `sort`, since the `vale --sort` is not stable when there is more than one issue on a line (only in the tests where this is an issue). That also makes it necessary to check the return code as a separate check.

### CODE REVIEW

**Comment by ftisiot** [comment]
@TibsAtWork can you give me any hint on how to test this change?

**Comment by TibsAtWork** [comment]
On a Mac, install `shelltest` with
```
brew install shelltest
```
and then, in the top-level directory, run
```
shelltest .github/vale/tests/shelltest.test
```
and you should see
```
:.github/vale/tests/shelltest.test:1: [OK]
:.github/vale/tests/shelltest.test:2: [OK]
:.github/vale/tests/shelltest.test:3: [OK]
:.github/vale/tests/shelltest.test:4: [OK]
:.github/vale/tests/shelltest.test:5: [OK]
:.github/vale/tests/shelltest.test:6: [OK]
:.github/vale/tests/shelltest.test:7: [OK]
:.github/vale/tests/shelltest.test:8: [OK]

         Test Cases  Total
 Passed  8           8
 Failed  0           0
 Total   8           8
```

**Comment by lornajane** [comment]
@TibsAtWork do we need this change? I think we may need to advocate for it, find a reviewer, or somehow move it forward. I can't see it being picked up as it is.

**Comment by TibsAtWork** [comment]
I use this test-suite to validate that I've not broken anything when I add/change tests, so yes please.
I keep meaning to ask for someone to check it and merge it, but I figured it could wait with everyone being busy in the last parts of the "finishing the help transfer" work.
The instructions given (which are essentially those in the test file itself) should work.

**Comment by dewan-ahmed** [comment]
@TibsAtWork I can review this PR next week, if it's OK with you.

**Comment by TibsAtWork** [comment]
Thanks @dewan-ahmed, that would be wonderful.

**Review by dewan-ahmed — COMMENTED** [review]
Hi @TibsAtWork, here are the steps I followed:

1. Checked out this branch.
2. Installed shelltest (I actually had to use `brew install shelltestrunner` since brew could not find shelltest).
3. From the root of the DevPortal project, I ran `shelltest .github/vale/tests/shelltest.test`

Here is the result:
```
dewan.ahmed@Dewans-MacBook-Pro devportal % shelltest .github/vale/tests/shelltest.test
:.github/vale/tests/shelltest.test:1: [Failed]
ERROR: user error (/bin/sh: vale: command not found
 Command: 'vale --output=line --sort .github/vale/tests/good.rst' Exit code: 127)
:.github/vale/tests/shelltest.test:2: [Failed]
Command:
vale --output=line .github/vale/tests/bad.rst | sort
Expected stdout: 
.github/vale/tests/bad.rst:10:1:Aiven.common_replacements:Use 'InfluxDB' instead of 'influx'.
.github/vale/tests/bad.rst:11:1:Aiven.aiven_spelling:'influxdb' does not seem to be a recognised word
.github/vale/tests/bad.rst:11:1:Aiven.common_replacements:Use 'InfluxDB' instead of 'influxdb'.
.github/vale/tests/bad.rst:12:1:Aiven.aiven_spelling:'kakfa' does not seem to be a recognised word
.github/vale/tests/bad.rst:12:1:Aiven.common_replacements:Use 'Kafka' instead of 'kakfa'.
.github/vale/tests/...(1995 more)
Got stdout:      
Expected stderr: 

Got stderr:      
/bin/sh: vale: command not found

:.github/vale/tests/shelltest.test:3: [Failed]
ERROR: user error (/bin/sh: vale: command not found
 Command: 'vale --output=line --sort .github/vale/tests/bad.rst' Exit code: 127)
:.github/vale/tests/shelltest.test:4: [Failed]
ERROR: user error (/bin/sh: vale: command not found
 Command: 'vale --output=line --sort .github/vale/tests/first_ref_good.rst' Exit code: 127)
:.github/vale/tests/shelltest.test:5: [Failed]
Command:
vale --output=line .github/vale/tests/first_ref_bad.rst | sort
Expected stdout: 
.github/vale/tests/first_ref_bad.rst:10:25:Aiven.first_Cassandra_is_registered:At least one 'Cassandra' must be marked as ®
.github/vale/tests/first_ref_bad.rst:10:36:Aiven.first_OpenSearch_is_registered:At least one 'OpenSearch' must be marked as ®
.github/vale/tests/first_ref_bad.rst:10:48:Aiven.first_PostgreSQL_is_registered:At least one 'PostgreSQL' must be marked as ®
.github/vale/tests/first_ref_bad.rst:10:60:Aiven.first_InfluxDB_is_registered:At least one 'InfluxDB' must be marked as ®
.g...(1771 more)
Got stdout:      
Expected stderr: 

Got stderr:      
/bin/sh: vale: command not found

:.github/vale/tests/shelltest.test:6: [Failed]
ERROR: user error (/bin/sh: vale: command not found
 Command: 'vale --output=line --sort .github/vale/tests/first_ref_bad.rst' Exit code: 127)
:.github/vale/tests/shelltest.test:7: [Failed]
ERROR: user error (/bin/sh: vale: command not found
 Command: 'vale --output=line --sort .github/vale/tests/sentence_case_title_good.rst' Exit code: 127)
:.github/vale/tests/shelltest.test:8: [Failed]
ERROR: user error (/bin/sh: vale: command not found
 Command: 'vale --output=line --sort .github/vale/tests/sentence_case_title_bad.rst' Exit code: 127)

         Test Cases  Total      
 Passed  0           0          
 Failed  8           8          
 Total   8           8  
```

Does Vale need to be in the $PATH? For regular `make livehtml` or `make linkcheck`, I don't see such errors (/bin/sh: vale: command not found).

**Comment by TibsAtWork** [comment]
Ah - apologies! The curse of assumptions (on my part).
Yes, you need vale installed (`brew install vale`).
`make livehtml` and `make linkcheck` don't use vale - it's `make spell` that uses vale.

I've added a note to the comments at the start of `shelltest.test`

(just for myself, I double checked we'd remembered to say that in the README - it's at https://github.com/aiven/devportal/blob/main/README.rst#running-build-tasks-locally)
(I checked because I know I should re-read the README and CONTRIBUTING guides regularly myself!)

**Comment by TibsAtWork** [comment]
I've also fixed the `brew install shelltestrunner` command - you're right about what it should be (hmm - I wonder if it changed?)

**Comment by dewan-ahmed** [comment]
Works like a charm now:

```

         Test Cases  Total      
 Passed  8           8          
 Failed  0           0          
 Total   8           8  
```
Had to rebase the branch because I see the CloudFlare build fails.

**Review by dewan-ahmed — APPROVED** [review]
LGTM

Thanks @TibsAtWork

**Pull request merged**
