### PR TITLE
Add Sitemap

### PR DESCRIPTION
**Pull request by lornajane**
# What changed, and why it matters

We need a sitemap, this adds a plugin that generates one, and also advertises this in robots.txt

### CODE REVIEW

**Comment by gskhan** [comment]
👋  @lornajane 
is it possible to add `changefreq` and `priority` to the sitemap items. And if we can add `lastmod` it will be awesome but we don't even have it in the marketing site right now.

https://www.sitemaps.org/protocol.html

**Comment by lornajane** [comment]
I'm not sure what we'd do with priority, but (it and) the other two requests are open as issues on the project:
 - https://github.com/jdillard/sphinx-sitemap/issues/3
 - https://github.com/jdillard/sphinx-sitemap/issues/12

I suggest that we would need to build/contribute these ourselves. Should we deploy the sitemap as-is for now and then work on this, or do you want to wait until these features area also available?

**Comment by gskhan** [comment]
@lornajane ok, we can push without those, to start
but the robots file is pointing to /docs/sitemap.xml where I can only see the sitemap in /sitemap.xml
just making sure that's correct

**Comment by lornajane** [comment]
Good catch! Take another look now please?

**Review by gskhan — APPROVED** [review]
we're 👍

**Pull request merged**
